"""
Autora: Lydia Blanco Ruiz
Script con las traducciones al inglés.
"""

from .keys import (
    AVERAGE_TIME,
    COMMON_USER_LABEL_EN,
    LOG_IN_LABEL_EN,
    MARKDOWN_LABEL,
    QUERIES,
    SECRET_FIELD_TEXT_EN,
    SECRET_FIELD_TOKEN,
)

COMPARE_MODELS_EN = "Compare models"
APPLY_FILTERS_EN = "Apply filters"
BULK_DELETE_EN = "Bulk delete"
NEW_PASSWORD_LABEL_EN = "New password"

TRANSLATIONS_EN={
    "app.default_title": "My site",
    "app.welcome": "Welcome",
    "app.author": "Author: Lydia Blanco Ruiz",
    "common.email": "Email",
    f"common.{SECRET_FIELD_TOKEN}": SECRET_FIELD_TEXT_EN,
    "common.name": "Name",
    "common.country": "Country",
    "common.save_changes": "Save changes",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.actions": "Actions",
    "common.all": "All",
    "common.filter": "Filter",
    "common.clear": "Clear",
    "common.yes": "Yes",
    "common.no": "No",
    "common.view": "View",
    "common.download": "Download",
    "common.page": "Page {page} of {total_pages} ({total_items} {items_label})",
    "common.previous": "« Previous",
    "common.next": "Next »",
    "common.loading": "Loading...",
    "common.close": "Close",
    "validation.required": "This field is required.",
    "validation.email": "Enter a valid email address.",
    "validation.min_length_2": "Must be at least 2 characters long.",
    "validation.min_length_6": "Must be at least 6 characters long.",
    "validation.min_length_8": "Must be at least 8 characters long.",
    "validation.max_length_255": "Must not exceed 255 characters.",
    "validation.max_length_2000": "Must not exceed 2000 characters.",
    f"validation.{SECRET_FIELD_TOKEN}_security": "Must include uppercase, lowercase, and at least one number.",
    "validation.summary_title": "Please review the form errors.",
    "nav.hello": "Hello, {name}",
    "nav.admin": "Administrator",
    "nav.user": COMMON_USER_LABEL_EN,
    "nav.last_login": "Last login:",
    "nav.options": "Options",
    "nav.manage_documents": "Manage documents",
    "nav.manage_users": "Manage users",
    "nav.query_history": "Query history",
    "nav.edit_user": "User Profile",
    "nav.usage_stats": "Statistics",
    "nav.home": "Home",
    "nav.settings": "Settings",
    "nav.appearance": "Appearance",
    "nav.dark_mode": "Dark mode",
    "nav.light_mode": "Light mode",
    "nav.internationalization": "Internationalization",
    "nav.language": "Language",
    "nav.logout": "Log out",
    "nav.open_menu": "Open menu",
    "lang.es": "Spanish",
    "lang.en": "English",
    "landing.login": LOG_IN_LABEL_EN,
    "landing.signup": "Sign up",
    "landing.hero_badge": "Get answers to all your questions",
    "landing.hero_title": "Access key information about tenders.",
    "landing.hero_subtitle": "PythIA uses an LLM combined with a RAG system to locate precise information in the tender documents of the Provincial Council of Burgos Governing Board and generate clear, fast, contextualized answers about public procurement procedures.",
    "landing.get_access": "Get access",
    "landing.more_info": "More information",
    "landing.card_1_title": "Consult specific tender documents",
    "landing.card_1_text": "Get answers about the content of tender documents from the Provincial Council of Burgos Governing Board.",
    "landing.card_2_title": "Answers with LLM + RAG",
    "landing.card_2_text": "The system combines natural language generation with document-context retrieval to answer more accurately.",
    "landing.card_3_title": "Answers without hallucinations",
    "landing.card_3_text": "The system delivers answers without hallucinations and clearly indicates when a question falls outside the tender documents.",
    "landing.card_4_title": "Precise information retrieval",
    "landing.card_4_text": "Find clauses, requirements, and relevant data inside administrative documentation without manually reviewing the whole file.",
    "landing.card_5_title": "Fast and clear access",
    "landing.card_5_text": "Reduce document analysis time and make key information easier to consult in an agile, visual, structured way.",
    "auth.login_title": LOG_IN_LABEL_EN,
    "auth.login_submit": LOG_IN_LABEL_EN,
    "auth.no_account": "Don't have an account? Sign up",
    "auth.already_account": "Already have an account? Log in",
    "auth.forgot_password_link": "Forgot your password?",
    "auth.back_home": "Back to home",
    "auth.signup_title": "Sign up",
    "auth.signup_submit": "Create account",
    "auth.forgot_password_title": "Recover password",
    "auth.forgot_password_submit": "Recover password",
    "auth.back_login": "Back to login",
    "auth.reset_password_title": "Reset password",
    "auth.new_password_title": NEW_PASSWORD_LABEL_EN,
    "auth.reset_password_submit": "Change password",
    "auth.repeat_password": "Repeat password",
    "auth.new_password": NEW_PASSWORD_LABEL_EN,
    "auth.password_mismatch": "Passwords do not match",
    "auth.login_required": "You must log in to access this page.",
    "auth.invalid_credentials": "Incorrect email or password.",
    "auth.email_exists": "A user with that email already exists.",
    "auth.email_undeliverable": "This email address does not appear to be valid or deliverable.",
    "auth.email_not_registered": "There is no account registered with that email address.",
    "auth.recovery_subject": "Password recovery",
    "auth.recovery_body": "Hello {name},\n\nYou requested a password reset.\nOpen this link to create a new one:\n\n{reset_url}\n\nIf this wasn't you, please ignore this email.",
    "auth.recovery_sent": "We have sent a password recovery link.",
    "auth.invalid_reset_link_expired": "The recovery link is invalid or has expired.",
    "auth.invalid_reset_link": "The recovery link is invalid.",
    "auth.password_changed": "Password changed. You can now log in.",
    "user.edit_title": "User Profile",
    "user.avatar_alt": "Profile avatar",
    "user.profile_image": "Profile picture",
    "user.profile_image_help": "Accepted formats: JPG, PNG, or WEBP.",
    "user.delete_account": "Delete account",
    "user.account": "your account",
    f"user.leave_empty_{SECRET_FIELD_TOKEN}": "Leave blank to keep it unchanged",
    "user.cancel_edit": "Cancel",
    "users.title": "User management",
    "users.add": "Add user",
    "users.id": "ID",
    "users.admin_col": "Admin",
    "users.last_login_col": "Last login",
    "users.you": "You",
    "users.no_login": "No login yet",
    "users.remove_admin": "Remove admin",
    "users.make_admin": "Make admin",
    "users.delete_item": "user {name}",
    "users.filter_name_placeholder": "Search by name",
    "users.role_filter": "Type",
    "users.bulk_change_type": "Change type",
    "users.selected_users": "selected users",
    "users.select_all": "Select all",
    "users.select_user": "Select {name}",
    "users.empty_filtered": "No users match those filters.",
    "user.theme_mode": "Theme mode",
    "user.language": "Language",
    "user.language.es": "Spanish",
    "user.language.en": "English",
    "user.preferred_model": "Preferred model",
    "user.theme.system": "System",
    "user.theme.light": "Light",
    "user.theme.dark": "Dark",
    "user.profile_updated": "Profile updated successfully",
    "user.preferences": "User preferences",
    "validation.allowed_image_formats": "Only JPG, PNG or WEBP images are allowed.",
    "admin.create_user_title": "Create new user",
    "admin.create_user_submit": "Create user",
    "admin.create_user_email_placeholder": "email@example.com",
    "admin.back_users": "Back to user management",
    "admin.is_admin": "Administrator",
    "docs.manage_title": "Manage documents",
    "docs.page_title": "Uploaded documents",
    "docs.manage_subtitle": "Upload documents into the system, run web scraping, or update the vector database.",
    "docs.upload_label": "Upload one or more PDFs",
    "docs.upload_help": "Accepted format: PDF",
    "docs.upload_pdf_required": "Select at least one PDF.",
    "docs.upload_pdf_invalid": "Only PDF files are allowed.",
    "docs.choose_files": "Choose PDFs",
    "docs.no_files_selected": "No file selected",
    "docs.files_selected": "{count} files selected",
    "docs.actions_title": "Actions",
    "docs.upload_button_tooltip": "Upload the selected PDF files into the system.",
    "docs.scraping_button_tooltip": "Automatically download tender notices from the Public Sector Procurement Platform.",
    "docs.markdown_button_tooltip": "Convert pending PDF files to Markdown to improve indexing.",
    "docs.vector_button_tooltip": "Update the vector database with the new documents.",
    "docs.upload_button": "Upload documents",
    "docs.scraping_button": "Web scraping",
    "docs.markdown_button": "Convert pending files to Markdown",
    "docs.vector_button": "Update vector database",
    "docs.progress_aria": "Process progress",
    "docs.running_default": "Running process...",
    "docs.cancel_process": "Cancel process",
    "docs.loaded_title": "Uploaded documents",
    "docs.loaded_subtitle": "Review the status of each file and remove the ones you no longer need.",
    "docs.count": "{count} documents",
    "docs.empty": "There are no uploaded PDF documents.",
    "docs.file": "File",
    "docs.type": "Type",
    "docs.type_administrativo": "Administrative",
    "docs.type_tecnico": "Technical",
    "docs.type_unknown": "No type",
    "docs.filter_name_placeholder": "Search by name",
    "docs.selected_documents": "selected documents",
    "docs.size": "Size",
    "docs.uploaded": "Uploaded",
    "docs.chunks": "Chunks",
    "docs.status": "Status",
    "docs.status_cargado": "Not indexed",
    "docs.status_indexado": "Indexed",
    "docs.status_procesado": "Processing",
    "docs.status_fallido": "Failed",
    "docs.status_con markdown": MARKDOWN_LABEL,
    "docs.markdown_status": MARKDOWN_LABEL,
    "docs.indexed": "Indexed",
    "docs.not_indexed": "Not indexed",
    "docs.processing": "Processing",
    "docs.failed": "Failed",
    "docs.with_markdown": MARKDOWN_LABEL,
    "docs.without_markdown": "No Markdown",
    "docs.markdown_ready": "Converted",
    "docs.markdown_pending": "Pending",
    "docs.view_pdf": "View PDF",
    "docs.download_pdf": "Download PDF",
    "docs.view_markdown": "View Markdown",
    "docs.download_markdown": "Download Markdown",
    "history.title": "Query history",
    "history.empty_home": "Run your first query.",
    "history.empty": "There are no queries yet.",
    "history.query_button": "Query the model",
    "history.user": COMMON_USER_LABEL_EN,
    "history.date": "Date",
    "history.question": "Question",
    "history.document": "Document",
    "history.time": "Time (s)",
    "history.sort_label": "Sort by",
    "history.sort_date_desc": "Date: newest first",
    "history.sort_date_asc": "Date: oldest first",
    "history.sort_time_desc": "Time: longest first",
    "history.sort_time_asc": "Time: shortest first",
    "history.details": "Details",
    "history.delete_item": "query #{id}",
    "history.view_answer": "View answer",
    "history.answer": "Answer:",
    "history.chunks_details": "Used chunks - query #{id}",
    "history.best_fragment": "Best fragment (rank #1)",
    "history.file": "File:",
    "history.title_label": "Title:",
    "history.segment": "Segment:",
    "history.similarity": "Similarity:",
    "history.best_chunk_missing": "The best chunk content could not be recovered.",
    "history.top_chunks": "Top {shown} of {total} used chunks",
    "history.ranking": "Rank",
    "history.no_chunks": "This query has no associated chunks in the database.",
    "home.rag_logo_alt": "PythIA logo",
    "home.rag_banner_title": "QUERY THE MODEL",
    "home.rag_banner_subtitle_1": "GET ANSWERS TO ALL YOUR QUESTIONS",
    "home.rag_banner_subtitle_2": "ABOUT STATE TENDERS",
    "home.usage_summary_aria": "Usage summary",
    "home.month_calendar_aria": "Monthly calendar",
    "home.metric_streak_title": "Current streak",
    "home.metric_streak_label": "days connecting to the application",
    "home.metric_queries_title": QUERIES,
    "home.metric_queries_label": "queries made",
    "home.metric_models_title": "Models",
    "home.metric_models_label": "different models used",
    "home.metric_activity_title": "Activity",
    "home.metric_activity_label": "days with registered queries",
    "home.metric_avg_time_title": AVERAGE_TIME,
    "home.metric_avg_time_label": "per generated answer",
    "home.carousel_queries_aria": "Queries made",
    "home.carousel_models_aria": "Models used",
    "home.carousel_active_days_aria": "Active days",
    "home.queries_count_aria": "Queries made: {count}",
    "home.query_distribution_aria": "Query distribution",
    "home.last_query": "Last query",
    "home.full_history": "View full history",
    "home.query_unit": "queries",
    "home.donut_admin_title": "Queries",
    "home.donut_user_title": QUERIES,
    "home.donut_user_segment": QUERIES,
    "home.donut_global_segment": "Global rest",
    "stats.page_title": "Statistics",
    "stats.subtitle": "Check the charts to see model usage.",
    "stats.scope_global_short": "Global",
    "stats.scope_user_short": "Your usage",
    "stats.scope_global": "Statistics for global usage",
    "stats.scope_user": "Statistics for user {name}",
    "stats.section_ranking": "Ranking",
    "stats.section_comparison": "Comparison",
    "stats.section_geo": "Geographic data",
    "stats.unit_queries": "queries",
    "stats.unit_logins": "logins",
    "stats.filter_label": COMMON_USER_LABEL_EN,
    "stats.filter_all_users": "All users",
    "stats.filter_help": "Select a specific user or global usage",
    "stats.total_queries": "Total queries",
    "stats.average_time": AVERAGE_TIME,
    "stats.active_days": "Active days",
    "stats.last_query": "Last query",
    "stats.no_queries": "There are no queries yet to display statistics.",
    "stats.chart_monthly_queries": "Queries by month",
    "stats.chart_monthly_queries_help": "Shows monthly query volume over the last 12 months.",
    "stats.chart_monthly_toggle_label": "Change the queries by month visualization",
    "stats.chart_monthly_view_bars": "Bars",
    "stats.chart_monthly_view_calendar": "Calendar",
    "stats.chart_avg_time": "Average response time by month",
    "stats.chart_avg_time_help": "Click a month to see its weeks and a week to see its days.",
    "stats.chart_weekdays": "Queries by weekday",
    "stats.chart_weekdays_help": "Summarizes which days concentrate the most activity.",
    "stats.chart_hours": "Queries by hour",
    "stats.chart_hours_help": "Helps identify peak usage hours.",
    "stats.chart_hours_toggle_label": "Change the queries by hour visualization",
    "stats.chart_hours_view_bars": "Bars",
    "stats.chart_hours_view_heatmap": "Heatmap",
    "stats.chart_top_users": "Users with most queries",
    "stats.chart_top_users_help": "Available to administrators.",
    "stats.chart_top_logins": "Users with most logins",
    "stats.chart_user_comparison": "Compare users",
    "stats.chart_user_comparison_help": "Compare global model usage per user and show mean, median, and variance.",
    "stats.comparison_mean": "Mean",
    "stats.comparison_median": "Median",
    "stats.comparison_variance": "Variance",
    "stats.comparison_current_user": "Your user: {name}",
    "stats.comparison_global": "Global",
    "stats.comparison_filter_label": "Users to compare",
    "stats.comparison_filter_apply": "Apply",
    "stats.comparison_filter_help": "You can compare a single user or all registered users. To select multiple users, hold Ctrl.",
    "stats.chart_user_locations": "Users by country",
    "stats.chart_user_locations_help": "Countries are colored by the number of registered users.",
    "stats.map_users": "users",
    "stats.map_user_names": "Users",
    "stats.map_load_error": "The map could not be loaded.",
    "stats.day_0": "Mon",
    "stats.day_1": "Tue",
    "stats.day_2": "Wed",
    "stats.day_3": "Thu",
    "stats.day_4": "Fri",
    "stats.day_5": "Sat",
    "stats.day_6": "Sun",
    "stats.metric_seconds": "s",
    "stats.metric_no_data": "No data",
    "stats.drill_months": "Months",
    "stats.drill_week": "Week",
    "stats.drill_back": "Back",
    "modal.delete_title": "Confirm deletion",
    "modal.delete_subtitle": "This action cannot be undone.",
    "modal.delete_question": "Are you sure you want to delete {item}?",
    "modal.chunks_title": "Chunk details",
    "rag.page_title": "Query the model",
    "rag.open_page": "Run query",
    "rag.model_comparison": COMPARE_MODELS_EN,
    "rag.title": "Ask the model (RAG)",
    "rag.subtitle": "Ask clear questions about the tender documents. To force a specific case file, mention \"expediente <number>\". To limit the search, say \"technical specifications\" or \"administrative tender documents\".",
    "rag.model_label": "Model",
    "rag.question_label": "Question",
    "rag.question_placeholder": "Write your question about the tender documents...",
    "rag.ask_button": "Ask",
    "rag.cancel_button": "Cancel query",
    "rag.answer_title": "Answer",
    "rag.fragment_used": "Used fragment",
    "rag.no_answer": "No answer.",
    "rag.no_chunk": "No fragment could be recovered.",
    "rag.view_all_fragments": "View all",
    "rag.querying": "Querying...",
    "rag.sending": "Sending query...",
    "rag.cancelled": "Query cancelled.",
    "rag.failed": "The query failed.",
    "rag.status_error": "The query status could not be checked.",
    "rag.unexpected_error": "An unexpected error occurred.",
    "rag.cancel_error": "The query could not be cancelled.",
    "rag.models_available": "Models available to answer",
    "rag.compare_models_button": COMPARE_MODELS_EN,
    "rag.model_usage_title": "Model usage",
    "rag.model_usage_subtitle": "Usage over time by model in the application.",
    "rag.model_usage_aria": "Model usage chart",
    "rag.evaluation.title": "RAG evaluation",
    "rag.evaluation.subtitle": "Global evaluation metrics (RAGAS + embeddings).",
    "rag.evaluation.run_button": "Evaluate RAG",
    "rag.evaluation.refresh_button": "Refresh",
    "rag.evaluation.no_results": "There is no evaluation yet.",
    "rag.evaluation.running": "Running evaluation...",
    "rag.evaluation.failed": "Evaluation failed.",
    "rag.evaluation.progress_aria": "Evaluation progress",
    "rag.evaluation.view_detail": "View details",
    "rag.evaluation.detail_title": "RAG evaluation details",
    "rag.evaluation.detail_global": "Global metrics",
    "rag.evaluation.detail_by_question": "Per-question breakdown",
    "rag.evaluation.detail_metric": "Metric",
    "rag.evaluation.detail_embeddings": "Embeddings",
    "rag.evaluation.detail_final": "Final",
    "rag.evaluation.detail_question": "Question",
    "rag.evaluation.detail_answer": "Answer",
    "rag.evaluation.detail_ground_truth": "Ground truth",
    "rag.evaluation.detail_evidence": "Evidence",
    "rag.evaluation.detail_contexts": "Contexts",
    "rag.evaluation.metric.faithfulness": "Faithfulness",
    "rag.evaluation.metric.answer_relevancy": "Answer relevancy",
    "rag.evaluation.metric.answer_correctness": "Answer correctness",
    "rag.evaluation.metric.context_precision": "Context precision",
    "rag.evaluation.metric.context_recall": "Context recall",
    "rag.evaluation.metric.context_relevancy": "Context relevancy",
    "rag.model_usage_empty": "No usage data to display yet.",
    "rag.mode_chat": "Chat",
    "rag.mode_form": "Form",
    "rag.chat_question_tooltip": "You can specify an expediente and the document type in your question. Example: \"For expediente EXP-123, in the administrative specs, what is the budget?\"",
    "rag_default.expediente_tooltip": "Select the expediente you want to query. Leave it as \"Any\" to search across all of them.",
    "rag_default.doc_type_tooltip": "Filter by document type: administrative or technical. If you choose one, only expedientes with that type will be shown.",
    "rag_default.question_kind_tooltip": "Choose the question type (amounts, deadlines, solvency, criteria, etc.) to auto-generate the query.",
    "rag.invalid_question": "Write a valid question.",
    "rag.empty_question": "Write a question.",
    "rag.question_too_long": "The question is too long (max. 2000 characters).",
    "rag.preparing": "Preparing query...",
    "rag.starting": "Starting query...",
    "rag.queued": "Query queued.",
    "rag.done": "Query finished.",
    "rag.cancelling": "Cancelling query...",
    "rag.system_error": "An error occurred while querying the system. Please try again.",
    "rag.model_not_found_error": "The selected model could not be downloaded automatically. Check the connection or choose another model.",
    "rag.timeout_error": "The model is taking too long to respond. Try again in a few seconds.",
    "rag_default.page_title": "Guided queries",
    "rag_default.open_page": "Guided queries",
    "rag_default.title": "Guided query form",
    "rag_default.subtitle": "Choose a case file, document type, and frequent question to send a default query to the model.",
    "rag_default.expediente_label": "Case file",
    "rag_default.expediente_any": "General query (no case file)",
    "rag_default.expediente_help": "If you leave it empty, the question will be asked over the available tender documents in general.",
    "rag_default.summary_label": "Request document summary",
    "rag_default.doc_type_label": "Type",
    "rag_default.doc_type_any": "Any type",
    "rag_default.doc_type_admin": "Administrative",
    "rag_default.doc_type_technical": "Technical",
    "rag_default.question_kind_label": "Default question",
    "rag_default.question_general": "General information",
    "rag_default.question_amounts": "Amounts and prices",
    "rag_default.question_deadlines": "Deadlines and dates",
    "rag_default.question_solvency": "Solvency",
    "rag_default.question_criteria": "Award criteria",
    "rag_default.question_guarantees": "Guarantees",
    "rag_default.question_budget": "Budget and estimated value",
    "rag_default.question_duration": "Duration and extensions",
    "rag_default.question_penalties": "Penalties and breaches",
    "rag_default.question_submission": "Bid submission",
    "rag_default.preview_label": "Question to send",
    "model_stats.page_title": "Model comparison",
    "model_stats.title": "Model comparison",
    "model_stats.subtitle_global": "Measure tokens, response times, user usage, and CPU/GPU execution for each model.",
    "model_stats.subtitle_user": "Measure tokens, response times, and CPU/GPU execution for the models you have used.",
    "model_stats.back_to_rag": "Back to query",
    "model_stats.no_data": "There are no finished queries yet to compare models.",
    "model_stats.models": "Models",
    "model_stats.total_uses": "Uses",
    "model_stats.total_tokens": "Tokens",
    "model_stats.avg_time": AVERAGE_TIME,
    "model_stats.users": "Users",
    "model_stats.unknown_device": "No data",
    "model_stats.chart_uses": "Times each model has been used",
    "model_stats.chart_uses_help": "Compares query volume and how many distinct users used each model.",
    "model_stats.chart_tokens": "Tokens by model",
    "model_stats.chart_tokens_help": "Adds registered tokens or estimates them from question and answer text.",
    "model_stats.chart_avg_time": "Average response time by model",
    "model_stats.chart_avg_time_help": "Shows the average seconds each model takes to answer.",
    "model_stats.chart_device": "CPU/GPU execution by model",
    "model_stats.chart_device_help": "Groups queries by the device used by Ollama in each answer.",
    "jobs.already_finished": "The process has already finished.",
    "jobs.queued_short": "Queued",
    "jobs.cancelled_generic": "Process cancelled.",
    "jobs.done_generic": "Process finished.",
    "jobs.failed_generic": "The process failed.",
    "markdown.cancelling": "Cancelling Markdown conversion...",
    "markdown.cancelled": "Markdown conversion cancelled.",
    "markdown.starting": "Starting Markdown conversion...",
    "markdown.converting_doc": "Converting {name}...",
    "markdown.converting_doc_page": "Converting {name}... Page {page}/{total_pages}",
    "markdown.converting_default": "Converting document...",
    "markdown.starting_ui": "Starting Markdown conversion...",
    "markdown.no_job_id": "The process identifier was not received.",
    "markdown.start_error": "Markdown conversion could not be started.",
    "markdown.status_error": "The conversion status could not be checked.",
    "markdown.unknown_state": "Unknown conversion state.",
    "markdown.none_pending": "There were no pending documents to convert.",
    "markdown.done_stats": "Conversion completed. {count} documents converted.",
    "markdown.done_stats_with_failures": "Conversion completed. {count} documents converted and {failed} failed.",
    "markdown.done_email": "Markdown conversion finished successfully.",
    "markdown.failed": "Markdown conversion failed.",
    "markdown.failed_email": "Markdown conversion failed: {error}",
    "vector.cancelling": "Cancelling vector database update...",
    "vector.cancelled_by_user": "Update cancelled by the user.",
    "vector.updating": "Updating vector database... ({progress}%)",
    "vector.updating_doc": "Updating vector database... ({progress}%) - {name}",
    "vector.done_ui": "Vector database updated.",
    "vector.cancelled_ui": "Vector database update cancelled.",
    "vector.failed_ui": "Vector database update failed.{error_suffix}",
    "vector.unknown_state": "Unknown update state.",
    "vector.starting_ui": "Starting vector database update...",
    "vector.no_job_id": "The process identifier was not received.",
    "vector.start_error": "The update could not be started.",
    "vector.status_error": "The process status could not be checked.",
    "vector.done_email": "The vector database update finished successfully.",
    "vector.failed_email": "Qdrant update failed: {error}",
    "scraping.cancelling": "Cancelling web scraping...",
    "scraping.cancelled": "Web scraping cancelled.",
    "scraping.starting": "Starting web scraping...",
    "scraping.script_1": "Running script 1/2...",
    "scraping.script_2": "Running script 2/2...",
    "scraping.syncing": "Syncing PDFs into the database...",
    "scraping.done": "Web scraping finished.",
    "scraping.done_ui": "Web scraping completed.",
    "scraping.failed": "Web scraping failed.",
    "scraping.failed_ui": "Web scraping failed.{error_suffix}",
    "scraping.unknown_state": "Unknown scraping state.",
    "scraping.starting_ui": "Starting web scraping...",
    "scraping.no_job_id": "The scraping identifier was not received.",
    "scraping.start_error": "Web scraping could not be started.",
    "scraping.status_error": "The scraping status could not be checked.",
    "scraping.done_email": "Web scraping finished successfully.",
    "scraping.failed_email": "Web scraping failed: {error}",
    "process.cancel_error": "The process could not be cancelled.",
    "process.resume_tracking": "Resuming process tracking...",
    "errors.bad_request_title": "Invalid request",
    "errors.bad_request_message": "The request could not be processed. Please review the submitted data.",
    "errors.forbidden_title": "Access denied",
    "errors.forbidden_message": "You do not have permission to access this resource.",
    "errors.not_found_title": "Page not found",
    "errors.not_found_message": "The requested resource does not exist or is no longer available.",
    "errors.server_title": "Internal error",
    "errors.server_message": "An unexpected error occurred. Please try again later.",
    "nav.tutorial": "Tutorial",
    "tutorial.next": "Next",
    "tutorial.prev": "Previous",
    "tutorial.done": "Done",
    "tutorial.progress": "Step {{current}} of {{total}}",
    "tutorial.start.title": "Interactive tutorial",
    "tutorial.start.desc": "Click here whenever you want a quick guide to the application.",
    "tutorial.nav.home.title": "Home",
    "tutorial.nav.home.desc": "Go back to the home page to access the main features.",
    "tutorial.nav.history.title": "History",
    "tutorial.nav.history.desc": "Review previous questions and answers.",
    "tutorial.nav.profile.title": "Profile",
    "tutorial.nav.profile.desc": "Edit your profile and preferences.",
    "tutorial.nav.stats.title": "Statistics",
    "tutorial.nav.stats.desc": "Check usage metrics and charts.",
    "tutorial.nav.docs.title": "Documents",
    "tutorial.nav.docs.desc": "Manage documents (admins only).",
    "tutorial.nav.users.title": "Users",
    "tutorial.nav.users.desc": "Manage users (admins only).",
    "tutorial.nav.theme.title": "Theme",
    "tutorial.nav.theme.desc": "Switch between dark and light mode.",
    "tutorial.nav.i18n.title": "Internationalization",
    "tutorial.nav.i18n.desc": "Change the application language",
    "tutorial.nav.logout.title": "Log out",
    "tutorial.nav.logout.desc": "Sign out of your current session.",
    "tutorial.screen_overview.title": "Overview",
    "tutorial.screen_overview.desc": "This is where the main content for this screen is shown.",
    "tutorial.home.logo.title": "Redirect",
    "tutorial.home.logo.desc": "Click here whenever you want to go back to the home page.",
    "tutorial.home.menu.title": "Menu",
    "tutorial.home.menu.desc": "Click here whenever you want to open the menu.",
    "tutorial.home.rag.title": "Query",
    "tutorial.home.rag.desc": "Click here whenever you want to ask the model a question.",
    "tutorial.home.charts.title": "Usage charts",
    "tutorial.home.charts.desc": "These charts summarize how the application is being used.",
    "tutorial.home.history_link.title": "Full history",
    "tutorial.home.history_link.desc": "Click here to go to the query history page.",
    "tutorial.history.filter.title": "Filters",
    "tutorial.history.filter.desc": "Open or close the history filters.",
    "tutorial.history.apply.title": APPLY_FILTERS_EN,
    "tutorial.history.apply.desc": "Click here to filter the displayed queries.",
    "tutorial.history.delete.title": BULK_DELETE_EN,
    "tutorial.history.delete.desc": "Delete the selected queries (if any are checked).",
    "tutorial.stats.scope.title": "Scope",
    "tutorial.stats.scope.desc": "Switch user/scope to refresh the statistics.",
    "tutorial.stats.compare.title": "Compare",
    "tutorial.stats.user_vs_global.title": "User vs global",
    "tutorial.stats.user_vs_global.desc_admin": "Choose whether to view global usage or a specific user’s usage.",
    "tutorial.stats.user_vs_global.desc_user": "Choose whether to view global usage or your own usage.",
    "tutorial.stats.compare.desc": "Apply the selection to compare users.",
    "tutorial.stats.chart_monthly.title": "Monthly queries",
    "tutorial.stats.chart_monthly.desc": "Click a month to see its weeks, and a week to see its days.",
    "tutorial.stats.chart_calendar.title": "Calendar",
    "tutorial.stats.chart_calendar.desc": "See the day-by-day distribution within the selected month.",
    "tutorial.stats.chart_avg_time.title": "Average time",
    "tutorial.stats.chart_avg_time.desc": "Hover points to see more details.",
    "tutorial.stats.chart_weekdays.title": "Busiest weekdays",
    "tutorial.stats.chart_weekdays.desc": "Interact with the bars to see exact values.",
    "tutorial.stats.chart_hours.title": "Hours of use",
    "tutorial.stats.chart_hours.desc": "Switch views and hover to explore the data.",
    "tutorial.stats.chart_hours_heatmap.title": "Heatmap",
    "tutorial.stats.chart_hours_heatmap.desc": "Click here to switch to the heatmap view.",
    "tutorial.stats.chart_user_compare.title": "Comparison",
    "tutorial.stats.chart_user_compare.desc": "Explore the comparison to see mean, median, and variation.",
    "tutorial.stats.chart_locations.title": "User map",
    "tutorial.stats.chart_locations.desc": "Hover a country to see the number of users.",
    "tutorial.stats.ranking.title": "Ranking",
    "tutorial.stats.ranking.desc": "Check the usage and login rankings (admins only).",
    "tutorial.profile.save.title": "Save changes",
    "tutorial.profile.save.desc": "Save your profile information and preferences.",
    "tutorial.profile.delete.title": "Delete account",
    "tutorial.profile.delete.desc": "Open the confirmation to delete your account.",
    "tutorial.rag.models.title": "Model selector",
    "tutorial.rag.models.desc": "You can choose from multiple available LLM models.",
    "tutorial.rag.compare.title": COMPARE_MODELS_EN,
    "tutorial.rag.compare.desc": "Shows charts with statistics for each model.",
    "tutorial.rag.chat_tab.title": "Chat mode",
    "tutorial.rag.chat_tab.desc": "Direct conversation with the model: type and ask.",
    "tutorial.rag.form_tab.title": "Form mode",
    "tutorial.rag.form_tab.desc": "Guided query to help structure your question.",
    "tutorial.rag.chat.title": "Chat",
    "tutorial.rag.chat.desc": "Write your question here in chat mode.",
    "tutorial.rag.guided_form.title": "Form",
    "tutorial.rag.guided_form.desc": "Fill in the guided query fields here.",
    "tutorial.rag.ask.title": "Ask",
    "tutorial.rag.ask.desc": "Click here to send your question to the model.",
    "tutorial.rag.answer.title": "Answer",
    "tutorial.rag.answer.desc": "The generated answer will be shown here.",
    "tutorial.rag.fragments.title": "Fragments",
    "tutorial.rag.fragments.desc": "These are the retrieved fragments used to justify the answer.",
    "tutorial.rag.chat.ask.desc": "Click here to send your question in chat mode.",
    "tutorial.rag.chat.answer.desc": "The chat answer will be shown here.",
    "tutorial.rag.chat.fragments.desc": "These are the fragments used for the chat answer.",
    "tutorial.rag.form.ask.desc": "Click here to submit the form query.",
    "tutorial.rag.form.answer.desc": "The form answer will be shown here.",
    "tutorial.rag.form.fragments.desc": "These are the fragments used for the form answer.",
    "tutorial.rag.view_all.title": "View all",
    "tutorial.rag.view_all.desc": "Click to see all retrieved fragments.",
    "tutorial.model_stats.back.title": "Back to querying",
    "tutorial.model_stats.back.desc": "Go back to the query page to keep asking questions.",
    "tutorial.docs.choose.title": "Choose documents",
    "tutorial.docs.choose.desc": "Select one or more PDFs to upload to the application.",
    "tutorial.docs.upload.title": "Upload",
    "tutorial.docs.upload.desc": "Click to upload the selected documents.",
    "tutorial.docs.scraping.title": "Web scraping",
    "tutorial.docs.scraping.desc": "Click to automatically fetch documents from the web (depending on configuration).",
    "tutorial.docs.markdown.title": "Convert to Markdown",
    "tutorial.docs.markdown.desc": "Convert pending documents to Markdown to improve processing.",
    "tutorial.docs.vector.title": "Update vector database",
    "tutorial.docs.vector.desc": "Update the vector database so the RAG can retrieve relevant fragments.",
    "tutorial.docs.filter.title": "Filters",
    "tutorial.docs.filter.desc": "Open or close the document filters.",
    "tutorial.docs.apply.title": APPLY_FILTERS_EN,
    "tutorial.docs.apply.desc": "Click here to filter the displayed documents.",
    "tutorial.docs.delete.title": BULK_DELETE_EN,
    "tutorial.docs.delete.desc": "Delete the selected documents (if any are checked).",
    "tutorial.users.filter.title": "Filters",
    "tutorial.users.filter.desc": "Open or close the user filters.",
    "tutorial.users.apply.title": APPLY_FILTERS_EN,
    "tutorial.users.apply.desc": "Click here to filter the displayed users.",
    "tutorial.users.bulk_toggle.title": "Change type",
    "tutorial.users.bulk_toggle.desc": "Change the role (admin/user) of the selected users.",
    "tutorial.users.bulk_delete.title": BULK_DELETE_EN,
    "tutorial.users.bulk_delete.desc": "Delete the selected users (if any are checked).",
    "tutorial.auth.name.title": "Name",
    "tutorial.auth.email.title": "Email address",
    "tutorial.auth.country.title": "Country",
    "tutorial.auth.password.title": "Password",
    "tutorial.auth.confirm_password.title": "Confirm password",
    "tutorial.auth.submit.title": "Submit form",
    "tutorial.auth.login.email.desc": "Enter the email address you registered with, using a valid format such as name@domain.com.",
    "tutorial.auth.login.password.desc": "Type your password with uppercase letters, lowercase letters, and numbers exactly as you created it.",
    "tutorial.auth.login.submit.desc": "Click here once the email and password are complete to log in.",
    "tutorial.auth.signup.name.desc": "Enter your name with at least two characters so your account can be identified.",
    "tutorial.auth.signup.email.desc": "Use a real, valid email address, for example name@domain.com. You will need it to recover your account.",
    "tutorial.auth.signup.country.desc": "Select your country to associate the account with the correct location.",
    "tutorial.auth.signup.password.desc": "Create a password of at least 8 characters with one uppercase letter, one lowercase letter, and at least one number.",
    "tutorial.auth.signup.confirm_password.desc": "Repeat the exact same password to confirm there are no typing mistakes.",
    "tutorial.auth.signup.submit.desc": "Click here once all fields are complete and valid to create your account.",
    "tutorial.auth.forgot.email.desc": "Enter the email address linked to your account to receive the recovery link.",
    "tutorial.auth.forgot.submit.desc": "Click here to request the password recovery link.",
    "tutorial.auth.new_password.title": NEW_PASSWORD_LABEL_EN,
    "tutorial.auth.reset.password.desc": "Enter a new password of at least 8 characters with one uppercase letter, one lowercase letter, and at least one number.",
    "tutorial.auth.reset.confirm_password.desc": "Type the exact same password again to confirm the change without mistakes.",
    "tutorial.auth.reset.submit.desc": "Click here when the new password and its confirmation match to save the change.",
    "tutorial.error.no_driver": "Could not load the tutorial (Driver.js not available). Check your connection or content blockers.",
    "tutorial.error.no_steps": "No tutorial steps are available for this screen.",
    "tutorial.fab_tooltip": "View an interactive tutorial on how to use this page",
}
