"""
Autora: Lydia Blanco Ruiz
Script con las traducciones a español.
"""
from .keys import (
    COMMON_USER_LABEL_ES,
    CONSULTAS,
    MARKDOWN_LABEL,
    SECRET_FIELD_TEXT_ES,
    SECRET_FIELD_TOKEN,
    TIEMPO,
)

STATS_TITLE_ES = "Estadísticas"
APPLY_FILTERS_ES = "Aplicar filtros"
BULK_DELETE_ES = "Borrado masivo"

TRANSLATIONS_ES = {
    "app.default_title": "Mi web",
    "app.welcome": "Bienvenido",
    "app.author": "Autora: Lydia Blanco Ruiz",
    "common.email": "Email",
    f"common.{SECRET_FIELD_TOKEN}": SECRET_FIELD_TEXT_ES,
    "common.name": "Nombre",
    "common.country": "País",
    "common.save_changes": "Guardar cambios",
    "common.cancel": "Cancelar",
    "common.delete": "Borrar",
    "common.actions": "Acciones",
    "common.all": "Todos",
    "common.filter": "Filtrar",
    "common.clear": "Limpiar",
    "common.yes": "Sí",
    "common.no": "No",
    "common.view": "Ver",
    "common.download": "Descargar",
    "common.page": "Página {page} de {total_pages} ({total_items} {items_label})",
    "common.previous": "« Anterior",
    "common.next": "Siguiente »",
    "common.loading": "Cargando...",
    "common.close": "Cerrar",
    "validation.required": "Este campo es obligatorio.",
    "validation.email": "Introduce un correo electrónico válido.",
    "validation.min_length_2": "Debe tener al menos 2 caracteres.",
    "validation.min_length_6": "Debe tener al menos 6 caracteres.",
    "validation.min_length_8": "Debe tener al menos 8 caracteres.",
    "validation.max_length_255": "No puede superar los 255 caracteres.",
    "validation.max_length_2000": "No puede superar los 2000 caracteres.",
    f"validation.{SECRET_FIELD_TOKEN}_security": "Debe incluir mayúsculas, minúsculas y al menos un número.",
    "validation.summary_title": "Revisa los errores del formulario.",
    "nav.hello": "Hola, {name}",
    "nav.admin": "Administrador",
    "nav.user": COMMON_USER_LABEL_ES,
    "nav.last_login": "Último inicio:",
    "nav.options": "Opciones",
    "nav.manage_documents": "Administrar documentos",
    "nav.manage_users": "Administrar usuarios",
    "nav.query_history": "Historial de consultas",
    "nav.edit_user": "Perfil de Usuario",
    "nav.usage_stats": STATS_TITLE_ES,
    "nav.home": "Página principal",
    "nav.settings": "Configuración",
    "nav.appearance": "Apariencia",
    "nav.dark_mode": "Modo oscuro",
    "nav.light_mode": "Modo claro",
    "nav.internationalization": "Internacionalización",
    "nav.language": "Idioma",
    "nav.logout": "Cerrar sesión",
    "nav.open_menu": "Abrir menú",
    "lang.es": "Español",
    "lang.en": "Inglés",
    "landing.login": "Iniciar sesión",
    "landing.signup": "Registrarse",
    "landing.hero_badge": "Responde todas tus preguntas",
    "landing.hero_title": "Accede a información clave sobre las licitaciones.",
    "landing.hero_subtitle": "PythIA utiliza un modelo LLM combinado con un sistema RAG para localizar información precisa en los pliegos de la Junta de Gobierno de la Diputación Provincial de Burgos y generar respuestas claras, rápidas y contextualizadas sobre los procedimientos de contratación pública.",
    "landing.get_access": "Obtener acceso",
    "landing.more_info": "Más información",
    "landing.card_1_title": "Consulta pliegos concretos",
    "landing.card_1_text": "Obtén respuestas sobre el contenido de los pliegos de licitación de la Junta de Gobierno de la Diputación Provincial de Burgos.",
    "landing.card_2_title": "Respuestas con LLM + RAG",
    "landing.card_2_text": "El sistema combina generación de lenguaje natural con recuperación de contexto documental para responder con mayor precisión.",
    "landing.card_3_title": "Respuestas sin alucinaciones",
    "landing.card_3_text": "El sistema asegura respuestas sin alucinaciones indicando claramente cuando la pregunta se sale del contenido de los pliegos.",
    "landing.card_4_title": "Búsqueda precisa de información",
    "landing.card_4_text": "Localiza cláusulas, requisitos y datos relevantes dentro de la documentación administrativa sin revisar manualmente todo el expediente.",
    "landing.card_5_title": "Acceso rápido y claro",
    "landing.card_5_text": "Reduce el tiempo de análisis documental y facilita la consulta de información clave de forma ágil, visual y estructurada.",
    "auth.login_title": "Inicio de sesión",
    "auth.login_submit": "Iniciar sesión",
    "auth.no_account": "¿No tienes cuenta? Regístrate",
    "auth.already_account": "¿Ya tienes cuenta? Inicia sesión",
    f"auth.forgot_{SECRET_FIELD_TOKEN}_link": "¿Olvidaste tu contraseña?",
    "auth.back_home": "Volver al inicio",
    "auth.signup_title": "Registro",
    "auth.signup_submit": "Crear cuenta",
    f"auth.forgot_{SECRET_FIELD_TOKEN}_title": "Recuperar contraseña",
    f"auth.forgot_{SECRET_FIELD_TOKEN}_submit": "Recuperar contraseña",
    "auth.back_login": "Volver al login",
    f"auth.reset_{SECRET_FIELD_TOKEN}_title": "Restablecer contraseña",
    f"auth.new_{SECRET_FIELD_TOKEN}_title": "Nueva contraseña",
    f"auth.reset_{SECRET_FIELD_TOKEN}_submit": "Cambiar contraseña",
    f"auth.repeat_{SECRET_FIELD_TOKEN}": "Repite la contraseña",
    f"auth.new_{SECRET_FIELD_TOKEN}": "Nueva contraseña",
    f"auth.{SECRET_FIELD_TOKEN}_mismatch": "Las contraseñas no coinciden",
    "auth.login_required": "Debes iniciar sesión para acceder a esta página.",
    "auth.invalid_credentials": "Email o contraseña incorrectos.",
    "auth.email_exists": "Ya existe un usuario con ese email.",
    "auth.email_undeliverable": "El correo electrónico no parece válido o no se puede entregar.",
    "auth.email_not_registered": "No existe ninguna cuenta registrada con ese correo.",
    "auth.recovery_subject": "Recuperación de contraseña",
    "auth.recovery_body": "Hola {name},\n\nHas solicitado recuperar tu contraseña.\nAbre este enlace para crear una nueva:\n\n{reset_url}\n\nSi no lo has solicitado tú, ignora este correo.",
    "auth.recovery_sent": "Se ha enviado un enlace para recuperar la contraseña.",
    "auth.invalid_reset_link_expired": "El enlace de recuperación no es válido o ha caducado.",
    "auth.invalid_reset_link": "El enlace de recuperación no es válido.",
    f"auth.{SECRET_FIELD_TOKEN}_changed": "Contraseña cambiada. Ya puedes iniciar sesión.",
    "user.edit_title": "Perfil de Usuario",
    "user.avatar_alt": "Avatar de perfil",
    "user.profile_image": "Foto de perfil",
    "user.profile_image_help": "Formatos admitidos: JPG, PNG o WEBP.",
    "user.delete_account": "Eliminar cuenta",
    "user.account": "tu cuenta",
    "user.profile_updated": "Perfil actualizado correctamente",
    f"user.leave_empty_{SECRET_FIELD_TOKEN}": "Dejar vacío para no cambiarla",
    "user.cancel_edit": "Cancelar",
    "users.title": "Gestión de usuarios",
    "users.add": "Añadir usuario",
    "users.id": "ID",
    "users.admin_col": "Admin",
    "users.last_login_col": "Último login",
    "users.you": "Tú",
    "users.no_login": "Sin inicio",
    "users.remove_admin": "Quitar admin",
    "users.make_admin": "Hacer admin",
    "users.delete_item": "el usuario {name}",
    "users.filter_name_placeholder": "Buscar por nombre",
    "users.role_filter": "Tipo",
    "users.bulk_change_type": "Cambiar tipo",
    "users.selected_users": "usuarios seleccionados",
    "users.select_all": "Seleccionar todos",
    "users.select_user": "Seleccionar {name}",
    "users.empty_filtered": "No hay usuarios con esos filtros.",
    "user.theme_mode": "Modo visual",
    "user.language": "Idioma",
    "user.language.es": "Español",
    "user.language.en": "Inglés",
    "user.preferred_model": "Modelo preferido",
    "user.theme.system": "Sistema",
    "user.theme.light": "Claro",
    "user.theme.dark": "Oscuro",
    "user.preferences": "Preferencias de usuario",
    "validation.allowed_image_formats": "Solo se admiten imágenes JPG, PNG o WEBP.",
    "admin.create_user_title": "Crear nuevo usuario",
    "admin.create_user_submit": "Crear usuario",
    "admin.create_user_email_placeholder": "email@ejemplo.com",
    "admin.back_users": "Volver a gestión de usuarios",
    "admin.is_admin": "Administrador",
    "docs.manage_title": "Administrar documentos",
    "docs.page_title": "Documentos cargados",
    "docs.manage_subtitle": "Carga documentos en el sistema, ejecuta el web scraping o faliza la base de datos vectorial.",
    "docs.upload_label": "Carga uno o varios PDF",
    "docs.upload_help": "Formato admitido: PDF",
    "docs.upload_pdf_required": "Selecciona al menos un PDF.",
    "docs.upload_pdf_invalid": "Solo se admiten archivos PDF.",
    "docs.choose_files": "Elegir PDF",
    "docs.no_files_selected": "Ningún archivo seleccionado",
    "docs.files_selected": "{count} archivos seleccionados",
    "docs.actions_title": "Acciones",
    "docs.upload_button_tooltip": "Carga los PDF seleccionados al sistema",
    "docs.scraping_button_tooltip": "Descarga automáticamente las licitaciones de la plataforma de contratación del sector público",
    "docs.markdown_button_tooltip": "Convierte PDF pendientes a Markdown para mejorar la indexación.",
    "docs.vector_button_tooltip": "Actualiza la base de datos vectorial con los nuevos documentos.",
    "docs.upload_button": "Subir documentos",
    "docs.scraping_button": "Web Scraping",
    "docs.markdown_button": "Convertir pendientes a Markdown",
    "docs.vector_button": "Actualizar base vectorial",
    "docs.progress_aria": "Progreso del proceso",
    "docs.running_default": "Ejecutando proceso...",
    "docs.cancel_process": "Cancelar proceso",
    "docs.loaded_title": "Documentos cargados",
    "docs.loaded_subtitle": "Revisa el estado de cada archivo y elimina los que ya no necesites.",
    "docs.count": "{count} documentos",
    "docs.empty": "No hay documentos PDF cargados.",
    "docs.file": "Archivo",
    "docs.type": "Tipo",
    "docs.type_administrativo": "Administrativo",
    "docs.type_tecnico": "Técnico",
    "docs.type_unknown": "Sin tipo",
    "docs.filter_name_placeholder": "Buscar por nombre",
    "docs.selected_documents": "documentos seleccionados",
    "docs.size": "Tamaño",
    "docs.uploaded": "Cargado",
    "docs.chunks": "Chunks",
    "docs.status": "Estado",
    "docs.status_cargado": "Sin indexar",
    "docs.status_indexado": "Indexado",
    "docs.status_procesado": "Procesando",
    "docs.status_fallido": "Fallido",
    "docs.status_con markdown": MARKDOWN_LABEL,
    "docs.markdown_status": MARKDOWN_LABEL,
    "docs.indexed": "Indexado",
    "docs.not_indexed": "Sin indexar",
    "docs.processing": "Procesando",
    "docs.failed": "Fallido",
    "docs.with_markdown": MARKDOWN_LABEL,
    "docs.without_markdown": "Sin Markdown",
    "docs.markdown_ready": "Convertido",
    "docs.markdown_pending": "Pendiente",
    "docs.view_pdf": "Ver PDF",
    "docs.download_pdf": "Descargar PDF",
    "docs.view_markdown": "Ver Markdown",
    "docs.download_markdown": "Descargar Markdown",
    "history.title": "Historial de consultas",
    "history.empty_home": "Realiza tu primera consulta.",
    "history.empty": "No hay consultas todavía.",
    "history.query_button": "Consultar al modelo",
    "history.user": COMMON_USER_LABEL_ES,
    "history.date": "Fecha",
    "history.question": "Pregunta",
    "history.document": "Documento",
    "history.time": "Tiempo (s)",
    "history.sort_label": "Ordenar por",
    "history.sort_date_desc": "Fecha: mas reciente",
    "history.sort_date_asc": "Fecha: mas antigua",
    "history.sort_time_desc": "Tiempo: mayor duración",
    "history.sort_time_asc": "Tiempo: menor duración",
    "history.details": "Detalles",
    "history.delete_item": "la consulta #{id}",
    "history.view_answer": "Ver respuesta",
    "history.answer": "Respuesta:",
    "history.chunks_details": "Chunks usados - consulta #{id}",
    "history.best_fragment": "Mejor fragmento (ranking #1)",
    "history.file": "Archivo:",
    "history.title_label": "Título:",
    "history.segment": "Segmento:",
    "history.similarity": "Similitud:",
    "history.best_chunk_missing": "No se pudo recuperar el contenido del mejor chunk.",
    "history.top_chunks": "Top {shown} de {total} chunks usados",
    "history.ranking": "Ranking",
    "history.no_chunks": "Esta consulta no tiene chunks asociados en la base de datos.",
    "home.rag_logo_alt": "Logo de PythIA",
    "home.rag_banner_title": "CONSULTA AL MODELO",
    "home.rag_banner_subtitle_1": "RESPONDE TODAS TUS DUDAS",
    "home.rag_banner_subtitle_2": "SOBRE LAS LICITACIONES DEL ESTADO",
    "home.usage_summary_aria": "Resumen de uso",
    "home.month_calendar_aria": "Calendario del mes",
    "home.metric_streak_title": "Racha actual",
    "home.metric_streak_label": "días conectándote a la aplicación",
    "home.metric_queries_title": CONSULTAS,
    "home.metric_queries_label": "consultas realizadas",
    "home.metric_models_title": "Modelos",
    "home.metric_models_label": "modelos distintos usados",
    "home.metric_activity_title": "Actividad",
    "home.metric_activity_label": "días con consultas registradas",
    "home.metric_avg_time_title": TIEMPO,
    "home.metric_avg_time_label": "por respuesta generada",
    "home.carousel_queries_aria": "Consultas realizadas",
    "home.carousel_models_aria": "Modelos usados",
    "home.carousel_active_days_aria": "Días activos",
    "home.queries_count_aria": "Consultas realizadas: {count}",
    "home.query_distribution_aria": "Distribución de consultas",
    "home.last_query": "Última consulta",
    "home.full_history": "Ver historial completo",
    "home.query_unit": "consultas",
    "home.donut_admin_title": "Consultas",
    "home.donut_user_title": CONSULTAS,
    "home.donut_user_segment": CONSULTAS,
    "home.donut_global_segment": "Resto global",
    "stats.page_title": STATS_TITLE_ES,
    "stats.subtitle": "Consulta gráficas para ver el uso del modelo.",
    "stats.scope_global_short": "Global",
    "stats.scope_user_short": "Tu uso",
    "stats.scope_global": "Estadísticas del uso global",
    "stats.scope_user": "Estadísticas del usuario {name}",
    "stats.section_ranking": "Ranking",
    "stats.section_comparison": "Comparativa",
    "stats.section_geo": "Datos geográficos",
    "stats.unit_queries": "consultas",
    "stats.unit_logins": "accesos",
    "stats.filter_label": COMMON_USER_LABEL_ES,
    "stats.filter_all_users": "Todos los usuarios",
    "stats.filter_help": "Selecciona un usuario concreto o el uso global",
    "stats.total_queries": "Consultas totales",
    "stats.average_time": TIEMPO,
    "stats.active_days": "Días con actividad",
    "stats.last_query": "Última consulta",
    "stats.no_queries": "Todavía no hay consultas para mostrar estadísticas.",
    "stats.chart_monthly_queries": "Consultas por mes",
    "stats.chart_monthly_queries_help": "Muestra el volumen mensual de consultas durante los últimos 12 meses.",
    "stats.chart_monthly_toggle_label": "Cambiar visualización de consultas por mes",
    "stats.chart_monthly_view_bars": "Barras",
    "stats.chart_monthly_view_calendar": "Calendario",
    "stats.chart_avg_time": "Tiempo medio de respuesta por mes",
    "stats.chart_avg_time_help": "Pulsa un mes para ver sus semanas y una semana para ver sus días.",
    "stats.chart_weekdays": "Consultas por día de la semana",
    "stats.chart_weekdays_help": "Resume qué días concentran más actividad.",
    "stats.chart_hours": "Consultas por franja horaria",
    "stats.chart_hours_help": "Ayuda a identificar las horas de mayor uso.",
    "stats.chart_hours_toggle_label": "Cambiar visualización de consultas por franja horaria",
    "stats.chart_hours_view_bars": "Barras",
    "stats.chart_hours_view_heatmap": "Mapa de calor",
    "stats.chart_top_users": "Usuarios con más consultas",
    "stats.chart_top_users_help": "Disponible para administradores.",
    "stats.chart_top_logins": "Usuarios con más accesos",
    "stats.chart_user_comparison": "Comparar usuarios",
    "stats.chart_user_comparison_help": "Compara el consumo global del modelo por usuario y muestra media, mediana y varianza.",
    "stats.comparison_mean": "Media",
    "stats.comparison_median": "Mediana",
    "stats.comparison_variance": "Varianza",
    "stats.comparison_current_user": "Tu usuario: {name}",
    "stats.comparison_global": "Global",
    "stats.comparison_filter_label": "Usuarios a comparar",
    "stats.comparison_filter_apply": "Aplicar",
    "stats.comparison_filter_help": "Puedes comparar un único usuario o todos los usuarios registrados. Para seleccionar varios usuarios, mantén Ctrl pulsado.",
    "stats.chart_user_locations": "Usuarios por país",
    "stats.chart_user_locations_help": "Mapa de países coloreados según el número de usuarios registrados.",
    "stats.map_users": "usuarios",
    "stats.map_user_names": "Usuarios",
    "stats.map_load_error": "No se pudo cargar el mapa.",
    "stats.day_0": "Lun",
    "stats.day_1": "Mar",
    "stats.day_2": "Mié",
    "stats.day_3": "Jue",
    "stats.day_4": "Vie",
    "stats.day_5": "Sáb",
    "stats.day_6": "Dom",
    "stats.metric_seconds": "s",
    "stats.metric_no_data": "Sin datos",
    "stats.drill_months": "Meses",
    "stats.drill_week": "Semana",
    "stats.drill_back": "Volver",
    "modal.delete_title": "Confirmar borrado",
    "modal.delete_subtitle": "Esta acción no se puede deshacer.",
    "modal.delete_question": "¿Seguro que quieres borrar {item}?",
    "modal.chunks_title": "Detalles de chunks",
    "rag.page_title": "Consultar al modelo",
    "rag.open_page": "Realizar consulta",
    "rag.model_comparison": "Comparar modelos",
    "rag.title": "Preguntar al modelo (RAG)",
    "rag.subtitle": "Haz preguntas claras sobre los pliegos. Para forzar un expediente concreto, menciona \"expediente <número>\". Para limitar la búsqueda, indica \"pliego técnico\" o \"pliego administrativo\".",
    "rag.model_label": "Modelo",
    "rag.question_label": "Pregunta",
    "rag.question_placeholder": "Escribe tu pregunta sobre los pliegos...",
    "rag.ask_button": "Preguntar",
    "rag.cancel_button": "Cancelar consulta",
    "rag.answer_title": "Respuesta",
    "rag.fragment_used": "Fragmento usado",
    "rag.no_answer": "Sin respuesta.",
    "rag.no_chunk": "No se ha recuperado ningún fragmento.",
    "rag.view_all_fragments": "Ver todos",
    "rag.querying": "Consultando...",
    "rag.sending": "Enviando consulta...",
    "rag.cancelled": "Consulta cancelada.",
    "rag.failed": "La consulta ha fallado.",
    "rag.status_error": "No se pudo consultar el estado de la consulta.",
    "rag.unexpected_error": "Ha ocurrido un error.",
    "rag.cancel_error": "No se pudo cancelar la consulta.",
    "rag.models_available": "Modelos disponibles para responder",
    "rag.compare_models_button": "Compara los modelos",
    "rag.model_usage_title": "Uso de modelos",
    "rag.model_usage_subtitle": "Evolución de uso por modelo en la aplicación.",
    "rag.model_usage_aria": "Gráfica de uso de modelos",
    "rag.model_usage_empty": "Aún no hay datos de uso para mostrar.",
    "rag.mode_chat": "Chat",
    "rag.mode_form": "Formulario",
    "rag.chat_question_tooltip": "Puedes indicar un expediente y el tipo de pliego en la propia pregunta. Ejemplo: \"Para el expediente EXP-123, en el pliego administrativo, ¿cuál es el presupuesto?\"",
    "rag_default.expediente_tooltip": "Selecciona el expediente sobre el que quieres preguntar. Puedes dejarlo en \"Cualquiera\" para buscar en todos.",
    "rag_default.doc_type_tooltip": "Filtra el tipo de pliego: administrativo o técnico. Si eliges uno, se mostrarán expedientes con documentos de ese tipo.",
    "rag_default.question_kind_tooltip": "Elige la clase de pregunta (importes, plazos, solvencia, criterios, etc.) para generar automáticamente la consulta.",
    "rag.invalid_question": "Escribe una pregunta válida.",
    "rag.empty_question": "Escribe una pregunta.",
    "rag.question_too_long": "La pregunta es demasiado larga (máx. 2000 caracteres).",
    "rag.preparing": "Preparando consulta...",
    "rag.starting": "Iniciando consulta...",
    "rag.queued": "Consulta en cola.",
    "rag.done": "Consulta finalizada.",
    "rag.cancelling": "Cancelando consulta...",
    "rag.system_error": "Ha ocurrido un error consultando el sistema. Inténtalo de nuevo.",
    "rag.model_not_found_error": "No se pudo descargar automáticamente el modelo seleccionado. Revisa la conexión o elige otro modelo.",
    "rag.timeout_error": "El modelo está tardando demasiado en responder. Inténtalo de nuevo en unos segundos.",
    "rag_default.page_title": "Consultas guiadas",
    "rag_default.open_page": "Consultas guiadas",
    "rag_default.title": "Formulario de consultas guiadas",
    "rag_default.subtitle": "Elige un expediente, un tipo de pliego y una pregunta frecuente para lanzar una consulta por defecto al modelo.",
    "rag_default.expediente_label": "Expediente",
    "rag_default.expediente_any": "Consulta general (sin expediente)",
    "rag_default.expediente_help": "Si lo dejas vacío, la pregunta se hará sobre los pliegos disponibles en general.",
    "rag_default.summary_label": "Solicitar resumen del documento",
    "rag_default.doc_type_label": "Tipo",
    "rag_default.doc_type_any": "Cualquier tipo",
    "rag_default.doc_type_admin": "Administrativo",
    "rag_default.doc_type_technical": "Técnico",
    "rag_default.question_kind_label": "Pregunta tipo",
    "rag_default.question_general": "Información general",
    "rag_default.question_amounts": "Cantidades e importes",
    "rag_default.question_deadlines": "Plazos y fechas",
    "rag_default.question_solvency": "Solvencia",
    "rag_default.question_criteria": "Criterios de adjudicación",
    "rag_default.question_guarantees": "Garantías",
    "rag_default.question_budget": "Presupuesto y valor estimado",
    "rag_default.question_duration": "Duración y prórrogas",
    "rag_default.question_penalties": "Penalizaciones e incumplimientos",
    "rag_default.question_submission": "Presentación de ofertas",
    "rag_default.preview_label": "Pregunta que se enviara",
    "model_stats.page_title": "Comparativa de modelos",
    "model_stats.title": "Comparativa de modelos",
    "model_stats.subtitle_global": "Mide tokens, tiempos, uso por usuarios y ejecución CPU/GPU para cada modelo.",
    "model_stats.subtitle_user": "Mide tokens, tiempos y ejecución CPU/GPU de los modelos que has usado.",
    "model_stats.back_to_rag": "Volver a consultar",
    "model_stats.no_data": "Todavía no hay consultas finalizadas para comparar modelos.",
    "model_stats.models": "Modelos",
    "model_stats.total_uses": "Usos",
    "model_stats.total_tokens": "Tokens",
    "model_stats.avg_time": TIEMPO,
    "model_stats.users": "Usuarios",
    "model_stats.unknown_device": "Sin dato",
    "model_stats.chart_uses": "Veces que se ha usado cada modelo",
    "model_stats.chart_uses_help": "Compara el volumen de consultas y cuántos usuarios distintos han usado cada modelo.",
    "model_stats.chart_tokens": "Tokens por modelo",
    "model_stats.chart_tokens_help": "Suma los tokens registrados o estimados a partir de pregunta y respuesta.",
    "model_stats.chart_avg_time": "Tiempo medio de respuesta por modelo",
    "model_stats.chart_avg_time_help": "Muestra el promedio de segundos que tarda cada modelo en responder.",
    "model_stats.chart_device": "Ejecución CPU/GPU por modelo",
    "model_stats.chart_device_help": "Agrupa las consultas según el dispositivo usado por Ollama en cada respuesta.",
    "jobs.already_finished": "El proceso ya ha terminado.",
    "jobs.queued_short": "En cola",
    "jobs.cancelled_generic": "Proceso cancelado.",
    "jobs.done_generic": "Proceso finalizado.",
    "jobs.failed_generic": "El proceso ha fallado.",
    "markdown.cancelling": "Cancelando conversión a Markdown...",
    "markdown.cancelled": "Conversión a Markdown cancelada.",
    "markdown.starting": "Iniciando conversión a Markdown...",
    "markdown.converting_doc": "Convirtiendo {name}...",
    "markdown.converting_doc_page": "Convirtiendo {name}... Página {page}/{total_pages}",
    "markdown.converting_default": "Convirtiendo documento...",
    "markdown.starting_ui": "Lanzando conversión a Markdown...",
    "markdown.no_job_id": "No se recibió el identificador del proceso.",
    "markdown.start_error": "No se pudo iniciar la conversión a Markdown.",
    "markdown.status_error": "No se pudo consultar el estado de la conversión.",
    "markdown.unknown_state": "Estado de conversión desconocido.",
    "markdown.none_pending": "No había documentos pendientes de convertir.",
    "markdown.done_stats": "Conversión completada. {count} documentos convertidos.",
    "markdown.done_stats_with_failures": "Conversión completada. {count} documentos convertidos y {failed} con error.",
    "markdown.done_email": "La conversión a Markdown ha terminado correctamente.",
    "markdown.failed": "Falló la conversión a Markdown.",
    "markdown.failed_email": "La conversión a Markdown ha fallado: {error}",
    "vector.cancelling": "Cancelando actualización vectorial...",
    "vector.cancelled_by_user": "Actualización cancelada por el usuario.",
    "vector.updating": "Actualizando base vectorial... ({progress}%)",
    "vector.updating_doc": "Actualizando base vectorial... ({progress}%) - {name}",
    "vector.done_ui": "Base vectorial actualizada.",
    "vector.cancelled_ui": "Actualización vectorial cancelada.",
    "vector.failed_ui": "Falló la actualización de la base vectorial.{error_suffix}",
    "vector.unknown_state": "Estado de actualización desconocido.",
    "vector.starting_ui": "Lanzando actualización de base vectorial...",
    "vector.no_job_id": "No se recibió el identificador del proceso.",
    "vector.start_error": "No se pudo iniciar la actualización.",
    "vector.status_error": "No se pudo consultar el estado del proceso.",
    "vector.done_email": "La actualización de la base de datos vectorial ha terminado correctamente.",
    "vector.failed_email": "La actualización de Qdrant ha fallado: {error}",
    "scraping.cancelling": "Cancelando web scraping...",
    "scraping.cancelled": "Web scraping cancelado.",
    "scraping.starting": "Iniciando web scraping...",
    "scraping.script_1": "Ejecutando script 1/2...",
    "scraping.script_2": "Ejecutando script 2/2...",
    "scraping.syncing": "Sincronizando PDFs en la base de datos...",
    "scraping.done": "Web scraping terminado.",
    "scraping.done_ui": "Web scraping completado.",
    "scraping.failed": "Falló el web scraping.",
    "scraping.failed_ui": "Falló el web scraping.{error_suffix}",
    "scraping.unknown_state": "Estado de scraping desconocido.",
    "scraping.starting_ui": "Lanzando web scraping...",
    "scraping.no_job_id": "No se recibió el identificador del scraping.",
    "scraping.start_error": "No se pudo iniciar el web scraping.",
    "scraping.status_error": "No se pudo consultar el estado del scraping.",
    "scraping.done_email": "El web scraping ha terminado correctamente.",
    "scraping.failed_email": "El web scraping ha fallado: {error}",
    "process.cancel_error": "No se pudo cancelar el proceso.",
    "process.resume_tracking": "Reanudando seguimiento del proceso...",
    "errors.bad_request_title": "Solicitud no válida",
    "errors.bad_request_message": "La solicitud no se ha podido procesar. Revisa los datos enviados.",
    "errors.forbidden_title": "Acceso denegado",
    "errors.forbidden_message": "No tienes permisos para acceder a este recurso.",
    "errors.not_found_title": "Página no encontrada",
    "errors.not_found_message": "El recurso solicitado no existe o ya no está disponible.",
    "errors.server_title": "Error interno",
    "errors.server_message": "Ha ocurrido un error inesperado. Inténtalo de nuevo más tarde.",
    "nav.tutorial": "Tutorial",
    "tutorial.next": "Siguiente",
    "tutorial.prev": "Anterior",
    "tutorial.done": "Terminar",
    "tutorial.progress": "Paso {{current}} de {{total}}",
    "tutorial.start.title": "Tutorial interactivo",
    "tutorial.start.desc": "Pulsa aquí cuando quieras ver una guía rápida de la aplicación.",
    "tutorial.nav.home.title": "Página principal",
    "tutorial.nav.home.desc": "Vuelve al inicio para acceder a las funcionalidades principales.",
    "tutorial.nav.history.title": "Historial",
    "tutorial.nav.history.desc": "Consulta las preguntas y respuestas realizadas anteriormente.",
    "tutorial.nav.profile.title": "Perfil",
    "tutorial.nav.profile.desc": "Edita tu perfil y tus preferencias.",
    "tutorial.nav.stats.title": STATS_TITLE_ES,
    "tutorial.nav.stats.desc": "Revisa métricas de uso y gráficas.",
    "tutorial.nav.docs.title": "Documentos",
    "tutorial.nav.docs.desc": "Administra los documentos (solo administradores).",
    "tutorial.nav.users.title": "Usuarios",
    "tutorial.nav.users.desc": "Administra usuarios (solo administradores).",
    "tutorial.nav.theme.title": "Tema",
    "tutorial.nav.theme.desc": "Cambia entre modo oscuro y modo claro.",
    "tutorial.nav.i18n.title": "Internacionalización",
    "tutorial.nav.i18n.desc": "Cambia el idioma de la aplicación",
    "tutorial.nav.logout.title": "Cerrar sesión",
    "tutorial.nav.logout.desc": "Cierra tu sesión actual.",
    "tutorial.screen_overview.title": "Vista general",
    "tutorial.screen_overview.desc": "Aquí verás el contenido principal de esta pantalla.",
    "tutorial.home.logo.title": "Redirección",
    "tutorial.home.logo.desc": "Pulsa aquí cuando quieras volver a la página principal.",
    "tutorial.home.menu.title": "Menú",
    "tutorial.home.menu.desc": "Pulsa aquí cuando quieras abrir el menú.",
    "tutorial.home.rag.title": "Consulta",
    "tutorial.home.rag.desc": "Pulsa aquí cuando quieras realizar una consulta al modelo.",
    "tutorial.home.charts.title": "Gráficas de uso",
    "tutorial.home.charts.desc": "Estas gráficas resumen el uso de la aplicación.",
    "tutorial.home.history_link.title": "Historial completo",
    "tutorial.home.history_link.desc": "Pulsa aquí para ir a la página del historial de consultas.",
    "tutorial.history.filter.title": "Filtros",
    "tutorial.history.filter.desc": "Abre o cierra los filtros del historial.",
    "tutorial.history.apply.title": APPLY_FILTERS_ES,
    "tutorial.history.apply.desc": "Pulsa aquí para filtrar las consultas mostradas.",
    "tutorial.history.delete.title": BULK_DELETE_ES,
    "tutorial.history.delete.desc": "Borra las consultas seleccionadas (si hay alguna marcada).",
    "tutorial.stats.scope.title": "Ámbito",
    "tutorial.stats.scope.desc": "Cambia el usuario o ámbito para actualizar las estadísticas.",
    "tutorial.stats.compare.title": "Comparar",
    "tutorial.stats.user_vs_global.title": "Usuario vs global",
    "tutorial.stats.user_vs_global.desc_admin": "Elige si visualizar el uso global o el de un usuario concreto.",
    "tutorial.stats.user_vs_global.desc_user": "Elige si visualizar el uso global o el tuyo.",
    "tutorial.stats.compare.desc": "Aplica la selección para comparar usuarios.",
    "tutorial.stats.chart_monthly.title": "Consultas mensuales",
    "tutorial.stats.chart_monthly.desc": "Pulsa un mes para ver sus semanas y una semana para ver sus días.",
    "tutorial.stats.chart_calendar.title": "Calendario",
    "tutorial.stats.chart_calendar.desc": "Consulta la distribución diaria dentro del mes seleccionado.",
    "tutorial.stats.chart_avg_time.title": "Tiempo medio",
    "tutorial.stats.chart_avg_time.desc": "Pasa el ratón por los puntos para ver más detalle.",
    "tutorial.stats.chart_weekdays.title": "Días con más actividad",
    "tutorial.stats.chart_weekdays.desc": "Interactúa con las barras para ver valores exactos.",
    "tutorial.stats.chart_hours.title": "Horas de uso",
    "tutorial.stats.chart_hours.desc": "Cambia la vista y pasa el ratón para explorar los datos.",
    "tutorial.stats.chart_hours_heatmap.title": "Mapa de calor",
    "tutorial.stats.chart_hours_heatmap.desc": "Pulsa aquí para cambiar a la vista de mapa de calor.",
    "tutorial.stats.chart_user_compare.title": "Comparativa",
    "tutorial.stats.chart_user_compare.desc": "Explora la comparativa para ver media, mediana y variación.",
    "tutorial.stats.chart_locations.title": "Mapa de usuarios",
    "tutorial.stats.chart_locations.desc": "Pasa el ratón por un país para ver el número de usuarios.",
    "tutorial.stats.ranking.title": "Ranking",
    "tutorial.stats.ranking.desc": "Consulta el ranking de uso y accesos (solo administradores).",
    "tutorial.profile.save.title": "Guardar cambios",
    "tutorial.profile.save.desc": "Guarda la información y preferencias de tu perfil.",
    "tutorial.profile.delete.title": "Eliminar cuenta",
    "tutorial.profile.delete.desc": "Abre la confirmación para eliminar tu cuenta.",
    "tutorial.rag.models.title": "Selector de modelos",
    "tutorial.rag.models.desc": "Puedes elegir entre varios modelos LLM disponibles.",
    "tutorial.rag.compare.title": "Comparar modelos",
    "tutorial.rag.compare.desc": "Muestra gráficas con estadísticas de los modelos.",
    "tutorial.rag.chat_tab.title": "Modo chat",
    "tutorial.rag.chat_tab.desc": "Conversación directa con el modelo: escribe y pregunta.",
    "tutorial.rag.form_tab.title": "Modo formulario",
    "tutorial.rag.form_tab.desc": "Consulta guiada para estructurar mejor tu pregunta.",
    "tutorial.rag.chat.title": "Chat",
    "tutorial.rag.chat.desc": "Aquí redactas tu pregunta en modo chat.",
    "tutorial.rag.guided_form.title": "Formulario",
    "tutorial.rag.guided_form.desc": "Aquí completas los campos de la consulta guiada.",
    "tutorial.rag.ask.title": "Preguntar",
    "tutorial.rag.ask.desc": "Pulsa aquí para enviar la pregunta al modelo.",
    "tutorial.rag.answer.title": "Respuesta",
    "tutorial.rag.answer.desc": "Aquí se mostrará la respuesta generada.",
    "tutorial.rag.fragments.title": "Fragmentos",
    "tutorial.rag.fragments.desc": "Se muestran los fragmentos usados para justificar la respuesta.",
    "tutorial.rag.chat.ask.desc": "Pulsa aquí para enviar tu pregunta en modo chat.",
    "tutorial.rag.chat.answer.desc": "Aquí verás la respuesta generada para el chat.",
    "tutorial.rag.chat.fragments.desc": "Aquí se muestran los fragmentos usados en la respuesta del chat.",
    "tutorial.rag.form.ask.desc": "Pulsa aquí para enviar la consulta del formulario.",
    "tutorial.rag.form.answer.desc": "Aquí verás la respuesta generada para el formulario.",
    "tutorial.rag.form.fragments.desc": "Aquí se muestran los fragmentos usados en la respuesta del formulario.",
    "tutorial.rag.view_all.title": "Ver todos",
    "tutorial.rag.view_all.desc": "Pulsa para ver todos los fragmentos recuperados.",
    "tutorial.model_stats.back.title": "Volver a consultar",
    "tutorial.model_stats.back.desc": "Vuelve a la página de consulta para seguir preguntando.",
    "tutorial.docs.choose.title": "Elegir documentos",
    "tutorial.docs.choose.desc": "Selecciona uno o varios PDF para subirlos a la aplicación.",
    "tutorial.docs.upload.title": "Subir",
    "tutorial.docs.upload.desc": "Pulsa para subir los documentos seleccionados.",
    "tutorial.docs.scraping.title": "Web scraping",
    "tutorial.docs.scraping.desc": "Pulsa para descargar automáticamente documentos desde la web (según configuración).",
    "tutorial.docs.markdown.title": "Convertir a Markdown",
    "tutorial.docs.markdown.desc": "Convierte los documentos pendientes a Markdown para mejorar el procesamiento.",
    "tutorial.docs.vector.title": "Actualizar base vectorial",
    "tutorial.docs.vector.desc": "Actualiza la base de datos vectorial para que el RAG pueda recuperar fragmentos.",
    "tutorial.docs.filter.title": "Filtros",
    "tutorial.docs.filter.desc": "Abre o cierra los filtros de documentos.",
    "tutorial.docs.apply.title": APPLY_FILTERS_ES,
    "tutorial.docs.apply.desc": "Pulsa aquí para filtrar los documentos mostrados.",
    "tutorial.docs.delete.title": BULK_DELETE_ES,
    "tutorial.docs.delete.desc": "Borra los documentos seleccionados (si hay alguno marcado).",
    "tutorial.users.filter.title": "Filtros",
    "tutorial.users.filter.desc": "Abre o cierra los filtros de usuarios.",
    "tutorial.users.apply.title": APPLY_FILTERS_ES,
    "tutorial.users.apply.desc": "Pulsa aquí para filtrar los usuarios mostrados.",
    "tutorial.users.bulk_toggle.title": "Cambiar tipo",
    "tutorial.users.bulk_toggle.desc": "Cambia el tipo (admin/usuario) de los usuarios seleccionados.",
    "tutorial.users.bulk_delete.title": BULK_DELETE_ES,
    "tutorial.users.bulk_delete.desc": "Borra los usuarios seleccionados (si hay alguno marcado).",
    "tutorial.error.no_driver": "No se ha podido cargar el tutorial (Driver.js no disponible). Revisa tu conexión o bloqueadores de contenido.",
    "tutorial.error.no_steps": "No hay pasos de tutorial disponibles para esta pantalla.",
    "tutorial.fab_tooltip": "Ver un tutorial interactivo sobre el uso de la página",
}
