"""
Autora: Lydia Blanco Ruiz
Script con las traducciones a español.
"""
from .keys import COMMON_USER_LABEL_ES, MARKDOWN_LABEL, SECRET_FIELD_TOKEN, SECRET_FIELD_TEXT_ES
TRANSLATIONS_ES = {
    "app.default_title": "Mi web",
    "app.welcome": "Bienvenido",
    "app.author": "Autora: Lydia Blanco Ruiz",
    "common.email": "Email",
    f"common.{SECRET_FIELD_TOKEN}": SECRET_FIELD_TEXT_ES,
    "common.name": "Nombre",
    "common.save_changes": "Guardar cambios",
    "common.cancel": "Cancelar",
    "common.delete": "Borrar",
    "common.actions": "Acciones",
    "common.yes": "Sí",
    "common.no": "No",
    "common.view": "Ver",
    "common.download": "Descargar",
    "common.page": "Página {page} de {total_pages} ({total_items} {items_label})",
    "common.previous": "« Anterior",
    "common.next": "Siguiente »",
    "common.loading": "Cargando...",
    "common.close": "Cerrar",
    "validation.required": "Este campo es obligatorio.",
    "validation.email": "Introduce un correo electrónico válido.",
    "validation.min_length_2": "Debe tener al menos 2 caracteres.",
    "validation.min_length_6": "Debe tener al menos 6 caracteres.",
    "validation.min_length_8": "Debe tener al menos 8 caracteres.",
    "validation.max_length_255": "No puede superar los 255 caracteres.",
    "validation.max_length_2000": "No puede superar los 2000 caracteres.",
    f"validation.{SECRET_FIELD_TOKEN}_security": "Debe incluir mayúsculas, minúsculas y al menos un número.",
    "validation.summary_title": "Revisa los errores del formulario.",
    "nav.hello": "Hola, {name}",
    "nav.admin": "Administrador",
    "nav.user": COMMON_USER_LABEL_ES,
    "nav.last_login": "Último inicio:",
    "nav.options": "Opciones",
    "nav.manage_documents": "Administrar documentos",
    "nav.manage_users": "Administrar usuarios",
    "nav.query_history": "Historial de consultas",
    "nav.edit_user": "Editar usuario",
    "nav.usage_stats": "Estadísticas",
    "nav.home": "Página principal",
    "nav.settings": "Configuración",
    "nav.appearance": "Apariencia",
    "nav.dark_mode": "Modo oscuro",
    "nav.light_mode": "Modo claro",
    "nav.internationalization": "Internacionalización",
    "nav.language": "Idioma",
    "nav.logout": "Cerrar sesión",
    "nav.open_menu": "Abrir menú",
    "lang.es": "Español",
    "lang.en": "Inglés",
    "landing.login": "Iniciar sesión",
    "landing.signup": "Registrarse",
    "landing.hero_badge": "Responde todas tus preguntas",
    "landing.hero_title": "Accede a información clave sobre las licitaciones.",
    "landing.hero_subtitle": "PythIA utiliza un modelo LLM combinado con un sistema RAG para localizar información precisa en los pliegos de la Junta de Gobierno de la Diputación Provincial de Burgos y generar respuestas claras, rápidas y contextualizadas sobre los procedimientos de contratación pública.",
    "landing.get_access": "Obtener acceso",
    "landing.more_info": "Más información",
    "landing.card_1_title": "Consulta pliegos concretos",
    "landing.card_1_text": "Obtén respuestas sobre el contenido de los pliegos de licitación de la Junta de Gobierno de la Diputación Provincial de Burgos.",
    "landing.card_2_title": "Respuestas con LLM + RAG",
    "landing.card_2_text": "El sistema combina generación de lenguaje natural con recuperación de contexto documental para responder con mayor precisión.",
    "landing.card_3_title": "Respuestas sin alucinaciones",
    "landing.card_3_text": "El sistema asegura respuestas sin alucinaciones indicando claramente cuando la pregunta se sale del contenido de los pliegos.",
    "landing.card_4_title": "Búsqueda precisa de información",
    "landing.card_4_text": "Localiza cláusulas, requisitos y datos relevantes dentro de la documentación administrativa sin revisar manualmente todo el expediente.",
    "landing.card_5_title": "Acceso rápido y claro",
    "landing.card_5_text": "Reduce el tiempo de análisis documental y facilita la consulta de información clave de forma ágil, visual y estructurada.",
    "auth.login_title": "Inicio de sesión",
    "auth.login_submit": "Iniciar sesión",
    "auth.no_account": "¿No tienes cuenta? Regístrate",
    "auth.already_account": "¿Ya tienes cuenta? Inicia sesión",
    f"auth.forgot_{SECRET_FIELD_TOKEN}_link": "¿Olvidaste tu contraseña?",
    "auth.back_home": "Volver al inicio",
    "auth.signup_title": "Registro",
    "auth.signup_submit": "Crear cuenta",
    f"auth.forgot_{SECRET_FIELD_TOKEN}_title": "Recuperar contraseña",
    f"auth.forgot_{SECRET_FIELD_TOKEN}_submit": "Recuperar contraseña",
    "auth.back_login": "Volver al login",
    f"auth.reset_{SECRET_FIELD_TOKEN}_title": "Restablecer contraseña",
    f"auth.new_{SECRET_FIELD_TOKEN}_title": "Nueva contraseña",
    f"auth.reset_{SECRET_FIELD_TOKEN}_submit": "Cambiar contraseña",
    f"auth.repeat_{SECRET_FIELD_TOKEN}": "Repite la contraseña",
    f"auth.new_{SECRET_FIELD_TOKEN}": "Nueva contraseña",
    f"auth.{SECRET_FIELD_TOKEN}_mismatch": "Las contraseñas no coinciden",
    "auth.login_required": "Debes iniciar sesión para acceder a esta página.",
    "auth.invalid_credentials": "Email o contraseña incorrectos.",
    "auth.email_exists": "Ya existe un usuario con ese email.",
    "auth.recovery_subject": "Recuperación de contraseña",
    "auth.recovery_body": "Hola {name},\n\nHas solicitado recuperar tu contraseña.\nAbre este enlace para crear una nueva:\n\n{reset_url}\n\nSi no lo has solicitado tú, ignora este correo.",
    "auth.recovery_sent": "Si el email existe, hemos enviado un enlace para recuperar la contraseña.",
    "auth.invalid_reset_link_expired": "El enlace de recuperación no es válido o ha caducado.",
    "auth.invalid_reset_link": "El enlace de recuperación no es válido.",
    f"auth.{SECRET_FIELD_TOKEN}_changed": "Contraseña cambiada. Ya puedes iniciar sesión.",
    "user.edit_title": "Editar usuario",
    f"user.leave_empty_{SECRET_FIELD_TOKEN}": "Dejar vacío para no cambiarla",
    "user.cancel_edit": "Cancelar",
    "users.title": "Gestión de usuarios",
    "users.add": "Añadir usuario",
    "users.id": "ID",
    "users.admin_col": "Admin",
    "users.last_login_col": "Último login",
    "users.you": "Tú",
    "users.no_login": "Sin inicio",
    "users.remove_admin": "Quitar admin",
    "users.make_admin": "Hacer admin",
    "users.delete_item": "el usuario {name}",
    "admin.create_user_title": "Crear nuevo usuario",
    "admin.create_user_submit": "Crear usuario",
    "admin.back_users": "Volver a gestión de usuarios",
    "admin.is_admin": "Administrador",
    "docs.page_title": "Documentos cargados",
    "docs.manage_title": "Administrar documentos",
    "docs.manage_subtitle": "Carga documentos en el sistema, ejecuta el web scraping o actualiza la base de datos vectorial.",
    "docs.upload_label": "Carga uno o varios PDF",
    "docs.upload_help": "Formato admitido: PDF. Puedes seleccionar varios archivos a la vez.",
    "docs.upload_pdf_required": "Selecciona al menos un PDF.",
    "docs.upload_pdf_invalid": "Solo se admiten archivos PDF.",
    "docs.upload_button": "Subir documentos",
    "docs.scraping_button": "Web Scraping",
    "docs.markdown_button": "Convertir pendientes a Markdown",
    "docs.vector_button": "Actualizar base vectorial",
    "docs.progress_aria": "Progreso del proceso",
    "docs.running_default": "Ejecutando proceso...",
    "docs.cancel_process": "Cancelar proceso",
    "docs.loaded_title": "Documentos cargados",
    "docs.loaded_subtitle": "Revisa el estado de cada archivo y elimina los que ya no necesites.",
    "docs.count": "{count} documentos",
    "docs.empty": "No hay documentos PDF cargados.",
    "docs.file": "Archivo",
    "docs.size": "Tamaño",
    "docs.uploaded": "Cargado",
    "docs.chunks": "Chunks",
    "docs.status": "Estado",
    "docs.markdown_status": MARKDOWN_LABEL,
    "docs.indexed": "Indexado",
    "docs.not_indexed": "Sin indexar",
    "docs.processing": "Procesando",
    "docs.failed": "Fallido",
    "docs.with_markdown": MARKDOWN_LABEL,
    "docs.without_markdown": "Sin Markdown",
    "docs.markdown_ready": "Convertido",
    "docs.markdown_pending": "Pendiente",
    "docs.view_pdf": "Ver PDF",
    "docs.download_pdf": "Descargar PDF",
    "docs.view_markdown": "Ver Markdown",
    "docs.download_markdown": "Descargar Markdown",
    "history.title": "Historial de consultas",
    "history.empty_home": "Realiza tu primera consulta.",
    "history.empty": "No hay consultas todavía.",
    "history.query_button": "Consultar al modelo",
    "history.user": COMMON_USER_LABEL_ES,
    "history.date": "Fecha",
    "history.question": "Pregunta",
    "history.document": "Documento",
    "history.time": "Tiempo (s)",
    "history.details": "Detalles",
    "history.delete_item": "la consulta #{id}",
    "history.view_answer": "Ver respuesta",
    "history.answer": "Respuesta:",
    "history.chunks_details": "Chunks usados - consulta #{id}",
    "history.best_fragment": "Mejor fragmento (ranking #1)",
    "history.file": "Archivo:",
    "history.title_label": "Título:",
    "history.segment": "Segmento:",
    "history.similarity": "Similitud:",
    "history.best_chunk_missing": "No se pudo recuperar el contenido del mejor chunk.",
    "history.top_chunks": "Top {shown} de {total} chunks usados",
    "history.ranking": "Ranking",
    "history.no_chunks": "Esta consulta no tiene chunks asociados en la base de datos.",
    "stats.page_title": "Estadísticas",
    "stats.subtitle": "Consulta gráficas para ver el uso del modelo.",
    "stats.scope_global": "Estadísticas del uso global",
    "stats.scope_user": "Estadísticas del usuario {name}",
    "stats.filter_label": COMMON_USER_LABEL_ES,
    "stats.filter_all_users": "Todos los usuarios",
    "stats.filter_help": "Selecciona un usuario concreto o el uso global",
    "stats.total_queries": "Consultas totales",
    "stats.average_time": "Tiempo medio",
    "stats.active_days": "Días con actividad",
    "stats.last_query": "Última consulta",
    "stats.no_queries": "Todavía no hay consultas para mostrar estadísticas.",
    "stats.chart_monthly_queries": "Consultas por mes",
    "stats.chart_monthly_queries_help": "Muestra el volumen mensual de consultas durante los últimos 12 meses.",
    "stats.chart_monthly_toggle_label": "Cambiar visualización de consultas por mes",
    "stats.chart_monthly_view_bars": "Barras",
    "stats.chart_monthly_view_calendar": "Calendario",
    "stats.chart_avg_time": "Tiempo medio de respuesta por mes",
    "stats.chart_avg_time_help": "Permite detectar si el tiempo de respuesta del modelo está subiendo o bajando.",
    "stats.chart_weekdays": "Consultas por día de la semana",
    "stats.chart_weekdays_help": "Resume qué días concentran más actividad.",
    "stats.chart_hours": "Consultas por franja horaria",
    "stats.chart_hours_help": "Ayuda a identificar las horas de mayor uso.",
    "stats.chart_hours_toggle_label": "Cambiar visualización de consultas por franja horaria",
    "stats.chart_hours_view_bars": "Barras",
    "stats.chart_hours_view_heatmap": "Mapa de calor",
    "stats.chart_top_users": "Usuarios con más consultas",
    "stats.chart_top_users_help": "Disponible en la vista global para administradores.",
    "stats.day_0": "Lun",
    "stats.day_1": "Mar",
    "stats.day_2": "Mié",
    "stats.day_3": "Jue",
    "stats.day_4": "Vie",
    "stats.day_5": "Sáb",
    "stats.day_6": "Dom",
    "stats.metric_seconds": "s",
    "stats.metric_no_data": "Sin datos",
    "modal.delete_title": "Confirmar borrado",
    "modal.delete_subtitle": "Esta acción no se puede deshacer.",
    "modal.delete_question": "¿Seguro que quieres borrar {item}?",
    "modal.chunks_title": "Detalles de chunks",
    "rag.page_title": "Consultar al modelo",
    "rag.open_page": "Realizar consulta",
    "rag.title": "Preguntar al modelo (RAG)",
    "rag.subtitle": "Haz preguntas claras sobre los pliegos. Para forzar un expediente concreto, menciona \"expediente <numero>\". Para limitar la búsqueda, indica \"pliego técnico\" o \"pliego administrativo\".",
    "rag.question_label": "Pregunta",
    "rag.question_placeholder": "Escribe tu pregunta sobre los pliegos...",
    "rag.ask_button": "Preguntar",
    "rag.cancel_button": "Cancelar consulta",
    "rag.answer_title": "Respuesta",
    "rag.fragment_used": "Fragmento usado",
    "rag.no_answer": "Sin respuesta.",
    "rag.no_chunk": "No se ha recuperado ningún fragmento.",
    "rag.querying": "Consultando...",
    "rag.sending": "Enviando consulta...",
    "rag.cancelled": "Consulta cancelada.",
    "rag.failed": "La consulta ha fallado.",
    "rag.status_error": "No se pudo consultar el estado de la consulta.",
    "rag.unexpected_error": "Ha ocurrido un error.",
    "rag.cancel_error": "No se pudo cancelar la consulta.",
    "rag.invalid_question": "Escribe una pregunta válida.",
    "rag.empty_question": "Escribe una pregunta.",
    "rag.question_too_long": "La pregunta es demasiado larga (máx. 2000 caracteres).",
    "rag.preparing": "Preparando consulta...",
    "rag.starting": "Iniciando consulta...",
    "rag.queued": "Consulta en cola.",
    "rag.done": "Consulta finalizada.",
    "rag.cancelling": "Cancelando consulta...",
    "rag.system_error": "Ha ocurrido un error consultando el sistema. Inténtalo de nuevo.",
    "rag.timeout_error": "El modelo está tardando demasiado en responder. Inténtalo de nuevo en unos segundos.",
    "jobs.already_finished": "El proceso ya ha terminado.",
    "jobs.queued_short": "En cola",
    "jobs.cancelled_generic": "Proceso cancelado.",
    "jobs.failed_generic": "El proceso ha fallado.",
    "markdown.cancelling": "Cancelando conversión a Markdown...",
    "markdown.cancelled": "Conversión a Markdown cancelada.",
    "markdown.starting": "Iniciando conversión a Markdown...",
    "markdown.converting_doc": "Convirtiendo {name}...",
    "markdown.converting_doc_page": "Convirtiendo {name}... Página {page}/{total_pages}",
    "markdown.converting_default": "Convirtiendo documento...",
    "markdown.starting_ui": "Lanzando conversión a Markdown...",
    "markdown.no_job_id": "No se recibió el identificador del proceso.",
    "markdown.start_error": "No se pudo iniciar la conversión a Markdown.",
    "markdown.status_error": "No se pudo consultar el estado de la conversión.",
    "markdown.unknown_state": "Estado de conversión desconocido.",
    "markdown.none_pending": "No había documentos pendientes de convertir.",
    "markdown.done_stats": "Conversión completada. {count} documentos convertidos.",
    "markdown.done_stats_with_failures": "Conversión completada. {count} documentos convertidos y {failed} con error.",
    "markdown.done_email": "La conversión a Markdown ha terminado correctamente.",
    "markdown.failed": "Falló la conversión a Markdown.",
    "markdown.failed_email": "La conversión a Markdown ha fallado: {error}",
    "vector.cancelling": "Cancelando actualización vectorial...",
    "vector.cancelled_by_user": "Actualización cancelada por el usuario.",
    "vector.updating": "Actualizando base vectorial... ({progress}%)",
    "vector.updating_doc": "Actualizando base vectorial... ({progress}%) - {name}",
    "vector.done_ui": "Base vectorial actualizada.",
    "vector.cancelled_ui": "Actualización vectorial cancelada.",
    "vector.failed_ui": "Falló la actualización de la base vectorial.{error_suffix}",
    "vector.unknown_state": "Estado de actualización desconocido.",
    "vector.starting_ui": "Lanzando actualización de base vectorial...",
    "vector.no_job_id": "No se recibió el identificador del proceso.",
    "vector.start_error": "No se pudo iniciar la actualización.",
    "vector.status_error": "No se pudo consultar el estado del proceso.",
    "vector.done_email": "La actualización de la base de datos vectorial ha terminado correctamente.",
    "vector.failed_email": "La actualización de Qdrant ha fallado: {error}",
    "scraping.cancelling": "Cancelando web scraping...",
    "scraping.cancelled": "Web scraping cancelado.",
    "scraping.starting": "Iniciando web scraping...",
    "scraping.script_1": "Ejecutando script 1/2...",
    "scraping.script_2": "Ejecutando script 2/2...",
    "scraping.syncing": "Sincronizando PDFs en la base de datos...",
    "scraping.done": "Web scraping terminado.",
    "scraping.done_ui": "Web scraping completado.",
    "scraping.failed": "Falló el web scraping.",
    "scraping.failed_ui": "Falló el web scraping.{error_suffix}",
    "scraping.unknown_state": "Estado de scraping desconocido.",
    "scraping.starting_ui": "Lanzando web scraping...",
    "scraping.no_job_id": "No se recibió el identificador del scraping.",
    "scraping.start_error": "No se pudo iniciar el web scraping.",
    "scraping.status_error": "No se pudo consultar el estado del scraping.",
    "scraping.done_email": "El web scraping ha terminado correctamente.",
    "scraping.failed_email": "El web scraping ha fallado: {error}",
    "process.cancel_error": "No se pudo cancelar el proceso.",
    "process.resume_tracking": "Reanudando seguimiento del proceso...",
    "errors.bad_request_title": "Solicitud no válida",
    "errors.bad_request_message": "La solicitud no se ha podido procesar. Revisa los datos enviados.",
    "errors.forbidden_title": "Acceso denegado",
    "errors.forbidden_message": "No tienes permisos para acceder a este recurso.",
    "errors.not_found_title": "Página no encontrada",
    "errors.not_found_message": "El recurso solicitado no existe o ya no está disponible.",
    "errors.server_title": "Error interno",
    "errors.server_message": "Ha ocurrido un error inesperado. Inténtalo de nuevo más tarde.",
}