"""
Autora: Lydia Blanco Ruiz
Script con las traducciones al inglés.
"""

from .keys import COMMON_USER_LABEL_EN, LOG_IN_LABEL_EN, MARKDOWN_LABEL, SECRET_FIELD_TOKEN, SECRET_FIELD_TEXT_EN

TRANSLATIONS_EN={
    "app.default_title": "My site",
    "app.welcome": "Welcome",
    "app.author": "Author: Lydia Blanco Ruiz",
    "common.email": "Email",
    f"common.{SECRET_FIELD_TOKEN}": SECRET_FIELD_TEXT_EN,
    "common.name": "Name",
    "common.save_changes": "Save changes",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.actions": "Actions",
    "common.yes": "Yes",
    "common.no": "No",
    "common.view": "View",
    "common.download": "Download",
    "common.page": "Page {page} of {total_pages} ({total_items} {items_label})",
    "common.previous": "« Previous",
    "common.next": "Next »",
    "common.loading": "Loading...",
    "common.close": "Close",
    "validation.required": "This field is required.",
    "validation.email": "Enter a valid email address.",
    "validation.min_length_2": "Must be at least 2 characters long.",
    "validation.min_length_6": "Must be at least 6 characters long.",
    "validation.min_length_8": "Must be at least 8 characters long.",
    "validation.max_length_255": "Must not exceed 255 characters.",
    "validation.max_length_2000": "Must not exceed 2000 characters.",
    f"validation.{SECRET_FIELD_TOKEN}_security": "Must include uppercase, lowercase, and at least one number.",
    "validation.summary_title": "Please review the form errors.",
    "nav.hello": "Hello, {name}",
    "nav.admin": "Administrator",
    "nav.user": COMMON_USER_LABEL_EN,
    "nav.last_login": "Last login:",
    "nav.options": "Options",
    "nav.manage_documents": "Manage documents",
    "nav.manage_users": "Manage users",
    "nav.query_history": "Query history",
    "nav.edit_user": "Edit user",
    "nav.usage_stats": "Statistics",
    "nav.home": "Home",
    "nav.settings": "Settings",
    "nav.appearance": "Appearance",
    "nav.dark_mode": "Dark mode",
    "nav.light_mode": "Light mode",
    "nav.internationalization": "Internationalization",
    "nav.language": "Language",
    "nav.logout": "Log out",
    "nav.open_menu": "Open menu",
    "lang.es": "Spanish",
    "lang.en": "English",
    "landing.login": LOG_IN_LABEL_EN,
    "landing.signup": "Sign up",
    "landing.hero_badge": "Get answers to all your questions",
    "landing.hero_title": "Access key information about tenders.",
    "landing.hero_subtitle": "PythIA uses an LLM combined with a RAG system to locate precise information in the tender documents of the Provincial Council of Burgos Governing Board and generate clear, fast, contextualized answers about public procurement procedures.",
    "landing.get_access": "Get access",
    "landing.more_info": "More information",
    "landing.card_1_title": "Consult specific tender documents",
    "landing.card_1_text": "Get answers about the content of tender documents from the Provincial Council of Burgos Governing Board.",
    "landing.card_2_title": "Answers with LLM + RAG",
    "landing.card_2_text": "The system combines natural language generation with document-context retrieval to answer more accurately.",
    "landing.card_3_title": "Answers without hallucinations",
    "landing.card_3_text": "The system delivers answers without hallucinations and clearly indicates when a question falls outside the tender documents.",
    "landing.card_4_title": "Precise information retrieval",
    "landing.card_4_text": "Find clauses, requirements, and relevant data inside administrative documentation without manually reviewing the whole file.",
    "landing.card_5_title": "Fast and clear access",
    "landing.card_5_text": "Reduce document analysis time and make key information easier to consult in an agile, visual, structured way.",
    "auth.login_title": LOG_IN_LABEL_EN,
    "auth.login_submit": LOG_IN_LABEL_EN,
    "auth.no_account": "Don't have an account? Sign up",
    "auth.already_account": "Already have an account? Log in",
    "auth.forgot_password_link": "Forgot your password?",
    "auth.back_home": "Back to home",
    "auth.signup_title": "Sign up",
    "auth.signup_submit": "Create account",
    "auth.forgot_password_title": "Recover password",
    "auth.forgot_password_submit": "Recover password",
    "auth.back_login": "Back to login",
    "auth.reset_password_title": "Reset password",
    "auth.new_password_title": "New password",
    "auth.reset_password_submit": "Change password",
    "auth.repeat_password": "Repeat password",
    "auth.new_password": "New password",
    "auth.password_mismatch": "Passwords do not match",
    "auth.login_required": "You must log in to access this page.",
    "auth.invalid_credentials": "Incorrect email or password.",
    "auth.email_exists": "A user with that email already exists.",
    "auth.recovery_subject": "Password recovery",
    "auth.recovery_body": "Hello {name},\n\nYou requested a password reset.\nOpen this link to create a new one:\n\n{reset_url}\n\nIf this wasn't you, please ignore this email.",
    "auth.recovery_sent": "If the email exists, we have sent a password recovery link.",
    "auth.invalid_reset_link_expired": "The recovery link is invalid or has expired.",
    "auth.invalid_reset_link": "The recovery link is invalid.",
    "auth.password_changed": "Password changed. You can now log in.",
    "user.edit_title": "Edit user",
    f"user.leave_empty_{SECRET_FIELD_TOKEN}": "Leave blank to keep it unchanged",
    "user.cancel_edit": "Cancel",
    "users.title": "User management",
    "users.add": "Add user",
    "users.id": "ID",
    "users.admin_col": "Admin",
    "users.last_login_col": "Last login",
    "users.you": "You",
    "users.no_login": "No login yet",
    "users.remove_admin": "Remove admin",
    "users.make_admin": "Make admin",
    "users.delete_item": "user {name}",
    "admin.create_user_title": "Create new user",
    "admin.create_user_submit": "Create user",
    "admin.back_users": "Back to user management",
    "admin.is_admin": "Administrator",
    "docs.page_title": "Uploaded documents",
    "docs.manage_title": "Manage documents",
    "docs.manage_subtitle": "Upload documents into the system, run web scraping, or update the vector database.",
    "docs.upload_label": "Upload one or more PDFs",
    "docs.upload_help": "Accepted format: PDF. You can select multiple files at once.",
    "docs.upload_pdf_required": "Select at least one PDF.",
    "docs.upload_pdf_invalid": "Only PDF files are allowed.",
    "docs.upload_button": "Upload documents",
    "docs.scraping_button": "Web scraping",
    "docs.markdown_button": "Convert pending files to Markdown",
    "docs.vector_button": "Update vector database",
    "docs.progress_aria": "Process progress",
    "docs.running_default": "Running process...",
    "docs.cancel_process": "Cancel process",
    "docs.loaded_title": "Uploaded documents",
    "docs.loaded_subtitle": "Review the status of each file and remove the ones you no longer need.",
    "docs.count": "{count} documents",
    "docs.empty": "There are no uploaded PDF documents.",
    "docs.file": "File",
    "docs.size": "Size",
    "docs.uploaded": "Uploaded",
    "docs.chunks": "Chunks",
    "docs.status": "Status",
    "docs.markdown_status": MARKDOWN_LABEL,
    "docs.indexed": "Indexed",
    "docs.not_indexed": "Not indexed",
    "docs.processing": "Processing",
    "docs.failed": "Failed",
    "docs.with_markdown": MARKDOWN_LABEL,
    "docs.without_markdown": "No Markdown",
    "docs.markdown_ready": "Converted",
    "docs.markdown_pending": "Pending",
    "docs.view_pdf": "View PDF",
    "docs.download_pdf": "Download PDF",
    "docs.view_markdown": "View Markdown",
    "docs.download_markdown": "Download Markdown",
    "history.title": "Query history",
    "history.empty_home": "Run your first query.",
    "history.empty": "There are no queries yet.",
    "history.query_button": "Query the model",
    "history.user": COMMON_USER_LABEL_EN,
    "history.date": "Date",
    "history.question": "Question",
    "history.document": "Document",
    "history.time": "Time (s)",
    "history.details": "Details",
    "history.delete_item": "query #{id}",
    "history.view_answer": "View answer",
    "history.answer": "Answer:",
    "history.chunks_details": "Used chunks - query #{id}",
    "history.best_fragment": "Best fragment (rank #1)",
    "history.file": "File:",
    "history.title_label": "Title:",
    "history.segment": "Segment:",
    "history.similarity": "Similarity:",
    "history.best_chunk_missing": "The best chunk content could not be recovered.",
    "history.top_chunks": "Top {shown} of {total} used chunks",
    "history.ranking": "Rank",
    "history.no_chunks": "This query has no associated chunks in the database.",
    "stats.page_title": "Statistics",
    "stats.subtitle": "Check the charts to see model usage.",
    "stats.scope_global": "Statistics for global usage",
    "stats.scope_user": "Statistics for user {name}",
    "stats.filter_label": COMMON_USER_LABEL_EN,
    "stats.filter_all_users": "All users",
    "stats.filter_help": "Select a specific user or global usage",
    "stats.total_queries": "Total queries",
    "stats.average_time": "Average time",
    "stats.active_days": "Active days",
    "stats.last_query": "Last query",
    "stats.no_queries": "There are no queries yet to display statistics.",
    "stats.chart_monthly_queries": "Queries by month",
    "stats.chart_monthly_queries_help": "Shows monthly query volume over the last 12 months.",
    "stats.chart_monthly_toggle_label": "Change the queries by month visualization",
    "stats.chart_monthly_view_bars": "Bars",
    "stats.chart_monthly_view_calendar": "Calendar",
    "stats.chart_avg_time": "Average response time by month",
    "stats.chart_avg_time_help": "Helps detect whether model response time is rising or falling.",
    "stats.chart_weekdays": "Queries by weekday",
    "stats.chart_weekdays_help": "Summarizes which days concentrate the most activity.",
    "stats.chart_hours": "Queries by hour",
    "stats.chart_hours_help": "Helps identify peak usage hours.",
    "stats.chart_hours_toggle_label": "Change the queries by hour visualization",
    "stats.chart_hours_view_bars": "Bars",
    "stats.chart_hours_view_heatmap": "Heatmap",
    "stats.chart_top_users": "Users with most queries",
    "stats.chart_top_users_help": "Available in the global admin view.",
    "stats.day_0": "Mon",
    "stats.day_1": "Tue",
    "stats.day_2": "Wed",
    "stats.day_3": "Thu",
    "stats.day_4": "Fri",
    "stats.day_5": "Sat",
    "stats.day_6": "Sun",
    "stats.metric_seconds": "s",
    "stats.metric_no_data": "No data",
    "modal.delete_title": "Confirm deletion",
    "modal.delete_subtitle": "This action cannot be undone.",
    "modal.delete_question": "Are you sure you want to delete {item}?",
    "modal.chunks_title": "Chunk details",
    "rag.page_title": "Query the model",
    "rag.open_page": "Run query",
    "rag.title": "Ask the model (RAG)",
    "rag.subtitle": "Ask clear questions about the tender documents. To force a specific case file, mention \"expediente <number>\". To limit the search, say \"technical specifications\" or \"administrative tender documents\".",
    "rag.model_label": "Model",
    "rag.question_label": "Question",
    "rag.question_placeholder": "Write your question about the tender documents...",
    "rag.ask_button": "Ask",
    "rag.cancel_button": "Cancel query",
    "rag.answer_title": "Answer",
    "rag.fragment_used": "Used fragment",
    "rag.no_answer": "No answer.",
    "rag.no_chunk": "No fragment could be recovered.",
    "rag.querying": "Querying...",
    "rag.sending": "Sending query...",
    "rag.cancelled": "Query cancelled.",
    "rag.failed": "The query failed.",
    "rag.status_error": "The query status could not be checked.",
    "rag.unexpected_error": "An unexpected error occurred.",
    "rag.cancel_error": "The query could not be cancelled.",
    "rag.invalid_question": "Write a valid question.",
    "rag.empty_question": "Write a question.",
    "rag.question_too_long": "The question is too long (max. 2000 characters).",
    "rag.preparing": "Preparing query...",
    "rag.starting": "Starting query...",
    "rag.queued": "Query queued.",
    "rag.done": "Query finished.",
    "rag.cancelling": "Cancelling query...",
    "rag.system_error": "An error occurred while querying the system. Please try again.",
    "rag.model_not_found_error": "The selected model could not be downloaded automatically. Check the connection or choose another model.",
    "rag.timeout_error": "The model is taking too long to respond. Try again in a few seconds.",
    "jobs.already_finished": "The process has already finished.",
    "jobs.queued_short": "Queued",
    "jobs.cancelled_generic": "Process cancelled.",
    "jobs.failed_generic": "The process failed.",
    "markdown.cancelling": "Cancelling Markdown conversion...",
    "markdown.cancelled": "Markdown conversion cancelled.",
    "markdown.starting": "Starting Markdown conversion...",
    "markdown.converting_doc": "Converting {name}...",
    "markdown.converting_doc_page": "Converting {name}... Page {page}/{total_pages}",
    "markdown.converting_default": "Converting document...",
    "markdown.starting_ui": "Starting Markdown conversion...",
    "markdown.no_job_id": "The process identifier was not received.",
    "markdown.start_error": "Markdown conversion could not be started.",
    "markdown.status_error": "The conversion status could not be checked.",
    "markdown.unknown_state": "Unknown conversion state.",
    "markdown.none_pending": "There were no pending documents to convert.",
    "markdown.done_stats": "Conversion completed. {count} documents converted.",
    "markdown.done_stats_with_failures": "Conversion completed. {count} documents converted and {failed} failed.",
    "markdown.done_email": "Markdown conversion finished successfully.",
    "markdown.failed": "Markdown conversion failed.",
    "markdown.failed_email": "Markdown conversion failed: {error}",
    "vector.cancelling": "Cancelling vector database update...",
    "vector.cancelled_by_user": "Update cancelled by the user.",
    "vector.updating": "Updating vector database... ({progress}%)",
    "vector.updating_doc": "Updating vector database... ({progress}%) - {name}",
    "vector.done_ui": "Vector database updated.",
    "vector.cancelled_ui": "Vector database update cancelled.",
    "vector.failed_ui": "Vector database update failed.{error_suffix}",
    "vector.unknown_state": "Unknown update state.",
    "vector.starting_ui": "Starting vector database update...",
    "vector.no_job_id": "The process identifier was not received.",
    "vector.start_error": "The update could not be started.",
    "vector.status_error": "The process status could not be checked.",
    "vector.done_email": "The vector database update finished successfully.",
    "vector.failed_email": "Qdrant update failed: {error}",
    "scraping.cancelling": "Cancelling web scraping...",
    "scraping.cancelled": "Web scraping cancelled.",
    "scraping.starting": "Starting web scraping...",
    "scraping.script_1": "Running script 1/2...",
    "scraping.script_2": "Running script 2/2...",
    "scraping.syncing": "Syncing PDFs into the database...",
    "scraping.done": "Web scraping finished.",
    "scraping.done_ui": "Web scraping completed.",
    "scraping.failed": "Web scraping failed.",
    "scraping.failed_ui": "Web scraping failed.{error_suffix}",
    "scraping.unknown_state": "Unknown scraping state.",
    "scraping.starting_ui": "Starting web scraping...",
    "scraping.no_job_id": "The scraping identifier was not received.",
    "scraping.start_error": "Web scraping could not be started.",
    "scraping.status_error": "The scraping status could not be checked.",
    "scraping.done_email": "Web scraping finished successfully.",
    "scraping.failed_email": "Web scraping failed: {error}",
    "process.cancel_error": "The process could not be cancelled.",
    "process.resume_tracking": "Resuming process tracking...",
    "errors.bad_request_title": "Invalid request",
    "errors.bad_request_message": "The request could not be processed. Please review the submitted data.",
    "errors.forbidden_title": "Access denied",
    "errors.forbidden_message": "You do not have permission to access this resource.",
    "errors.not_found_title": "Page not found",
    "errors.not_found_message": "The requested resource does not exist or is no longer available.",
    "errors.server_title": "Internal error",
    "errors.server_message": "An unexpected error occurred. Please try again later.",
}
