"""create_table_consultaChunk

Revision ID: 1fb031988a12
Revises: 30877695294e
Create Date: 2026-01-24 10:51:25.180274

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1fb031988a12'
down_revision = '30877695294e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultaChunks',
    sa.Column('consulta_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('similitud', sa.Float(), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ),
    sa.PrimaryKeyConstraint('consulta_id', 'chunk_id'),
    sa.UniqueConstraint('consulta_id', 'ranking', name='uq_consulta_rank')
    )
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.drop_column('fragmentos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fragmentos', sa.JSON(), nullable=False))

    op.drop_table('consultaChunks')
    # ### end Alembic commands ###
