"""
Autora: Lydia Blanco Ruiz
Script de migración de Alembic para evolucionar el esquema de la base de datos.
"""

"""add chunk and embedding metadata tables

Revision ID: 30877695294e
Revises: c8c13480f8d8
Create Date: 2026-01-23 17:16:45.274057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30877695294e'
down_revision = 'c8c13480f8d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('qdrant_point_id', sa.String(length=36), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('doc_sha256', sa.String(length=100), nullable=False),
    sa.Column('n_chars', sa.Integer(), nullable=True),
    sa.Column('n_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'doc_sha256', 'segment_index', name='uq_chunk_doc_hash_seg')
    )
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chunks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_doc_sha256'), ['doc_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_qdrant_point_id'), ['qdrant_point_id'], unique=False)

    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('embedding_size', sa.Integer(), nullable=False),
    sa.Column('distance', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_embeddings_chunk_id'), ['chunk_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_embeddings_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_embeddings_created_at'))
        batch_op.drop_index(batch_op.f('ix_embeddings_chunk_id'))

    op.drop_table('embeddings')
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chunks_qdrant_point_id'))
        batch_op.drop_index(batch_op.f('ix_chunks_document_id'))
        batch_op.drop_index(batch_op.f('ix_chunks_doc_sha256'))
        batch_op.drop_index(batch_op.f('ix_chunks_created_at'))

    op.drop_table('chunks')
    # ### end Alembic commands ###
