"""Add user preferences

Revision ID: a965d9960be0
Revises: cc3d4e5f6a70
Create Date: 2026-05-12 13:25:44.453611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a965d9960be0'
down_revision = 'cc3d4e5f6a70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultaChunks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('consultaChunks_chunk_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'chunks', ['chunk_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_mode', sa.String(length=20), server_default='system', nullable=False))
        batch_op.add_column(sa.Column('preferred_model', sa.String(length=50), server_default='llama3.1:8b-instruct-q4_K_M', nullable=False))
        batch_op.add_column(sa.Column('language', sa.String(length=20), server_default='es', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('language')
        batch_op.drop_column('preferred_model')
        batch_op.drop_column('theme_mode')

    with op.batch_alter_table('consultaChunks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('consultaChunks_chunk_id_fkey'), 'chunks', ['chunk_id'], ['id'])

    # ### end Alembic commands ###
