"""
Autora: Lydia Blanco Ruiz
Script de migración de Alembic para evolucionar el esquema de la base de datos.
"""

"""create_tables_async

Revision ID: ae80c29fcbbc
Revises: 1fb031988a12
Create Date: 2026-01-28 13:40:40.036485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae80c29fcbbc'
down_revision = '1fb031988a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vector_update_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_doc', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vector_update_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vector_update_state_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vector_update_state_finished_at'), ['finished_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vector_update_state_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vector_update_state_status'), ['status'], unique=False)

    op.create_table('web_scraping_sate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('web_scraping_sate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_scraping_sate_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_web_scraping_sate_finished_at'), ['finished_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_web_scraping_sate_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_web_scraping_sate_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_scraping_sate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_scraping_sate_status'))
        batch_op.drop_index(batch_op.f('ix_web_scraping_sate_started_at'))
        batch_op.drop_index(batch_op.f('ix_web_scraping_sate_finished_at'))
        batch_op.drop_index(batch_op.f('ix_web_scraping_sate_created_at'))

    op.drop_table('web_scraping_sate')
    with op.batch_alter_table('vector_update_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vector_update_state_status'))
        batch_op.drop_index(batch_op.f('ix_vector_update_state_started_at'))
        batch_op.drop_index(batch_op.f('ix_vector_update_state_finished_at'))
        batch_op.drop_index(batch_op.f('ix_vector_update_state_created_at'))

    op.drop_table('vector_update_state')
    # ### end Alembic commands ###
