"""crear tabla consultas

Revision ID: b63c4b123c37
Revises: 7b8a876a95ae
Create Date: 2026-01-17 13:11:50.686295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63c4b123c37'
down_revision = '7b8a876a95ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=False),
    sa.Column('fragmentos', sa.JSON(), nullable=False),
    sa.Column('tiempo_respuestas', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultas_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultas_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultas_user_id'))
        batch_op.drop_index(batch_op.f('ix_consultas_created_at'))

    op.drop_table('consultas')
    # ### end Alembic commands ###
