"""
Autora: Lydia Blanco Ruiz
Script de migración de Alembic para evolucionar el esquema de la base de datos.
"""

"""restore fragmentos and user cascade

Revision ID: f3b1b7c9d2aa
Revises: ae80c29fcbbc
Create Date: 2026-03-11 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f3b1b7c9d2aa"
down_revision = "ae80c29fcbbc"
branch_labels = None
depends_on = None


def _has_column(inspector, table_name: str, column_name: str) -> bool:
    return any(column["name"] == column_name for column in inspector.get_columns(table_name))


def _foreign_key_for(inspector, table_name: str, constrained_column: str):
    for fk in inspector.get_foreign_keys(table_name):
        if fk.get("constrained_columns") == [constrained_column]:
            return fk
    return None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if not _has_column(inspector, "consultas", "fragmentos"):
        with op.batch_alter_table("consultas", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column(
                    "fragmentos",
                    sa.JSON(),
                    nullable=False,
                    server_default=sa.text("'[]'"),
                )
            )
        with op.batch_alter_table("consultas", schema=None) as batch_op:
            batch_op.alter_column("fragmentos", server_default=None)

    op.execute("UPDATE consultas SET fragmentos = '[]' WHERE fragmentos IS NULL")

    inspector = sa.inspect(bind)
    consultas_fk = _foreign_key_for(inspector, "consultas", "user_id")
    if consultas_fk and consultas_fk.get("options", {}).get("ondelete") != "CASCADE":
        with op.batch_alter_table("consultas", schema=None) as batch_op:
            if consultas_fk.get("name"):
                batch_op.drop_constraint(consultas_fk["name"], type_="foreignkey")
            batch_op.create_foreign_key(
                "fk_consultas_user_id_users",
                "users",
                ["user_id"],
                ["id"],
                ondelete="CASCADE",
            )

    inspector = sa.inspect(bind)
    consulta_chunks_fk = _foreign_key_for(inspector, "consultaChunks", "consulta_id")
    if consulta_chunks_fk and consulta_chunks_fk.get("options", {}).get("ondelete") != "CASCADE":
        with op.batch_alter_table("consultaChunks", schema=None) as batch_op:
            if consulta_chunks_fk.get("name"):
                batch_op.drop_constraint(consulta_chunks_fk["name"], type_="foreignkey")
            batch_op.create_foreign_key(
                "fk_consultaChunks_consulta_id_consultas",
                "consultas",
                ["consulta_id"],
                ["id"],
                ondelete="CASCADE",
            )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    consulta_chunks_fk = _foreign_key_for(inspector, "consultaChunks", "consulta_id")
    if consulta_chunks_fk and consulta_chunks_fk.get("options", {}).get("ondelete") == "CASCADE":
        with op.batch_alter_table("consultaChunks", schema=None) as batch_op:
            if consulta_chunks_fk.get("name"):
                batch_op.drop_constraint(consulta_chunks_fk["name"], type_="foreignkey")
            batch_op.create_foreign_key(
                "fk_consultaChunks_consulta_id_consultas",
                "consultas",
                ["consulta_id"],
                ["id"],
            )

    inspector = sa.inspect(bind)
    consultas_fk = _foreign_key_for(inspector, "consultas", "user_id")
    if consultas_fk and consultas_fk.get("options", {}).get("ondelete") == "CASCADE":
        with op.batch_alter_table("consultas", schema=None) as batch_op:
            if consultas_fk.get("name"):
                batch_op.drop_constraint(consultas_fk["name"], type_="foreignkey")
            batch_op.create_foreign_key(
                "fk_consultas_user_id_users",
                "users",
                ["user_id"],
                ["id"],
            )

    if _has_column(inspector, "consultas", "fragmentos"):
        with op.batch_alter_table("consultas", schema=None) as batch_op:
            batch_op.drop_column("fragmentos")
    
    # ### end Alembic commands ###
