services:
  db:
    image: postgres:16
    container_name: flask_db
    env_file:
      - .env
      - secret.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}

    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: flask_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrantdata:/qdrant/storage
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6333/readyz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 20s
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: flask_ollama
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-lc", "ollama list >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30

  ollama-init:
    image: ollama/ollama:latest
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ollama:/root/.ollama
    entrypoint: ["sh", "-lc"]
    command: ["ollama pull llama3.1:8b-instruct-q4_K_M"]
    restart: "no"

  web:
    build: .
    container_name: flask_web
    env_file: 
      - .env
      - secret.env
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    restart: unless-stopped
    volumes:
      - docsdata:/data

volumes:
  pgdata:
  qdrantdata:
  docsdata:
  ollama:
